{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxCtr_bgTemplate',
          'title':u'Ctr Data',
          'size':(720, 781),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(10, 520), 
    'size':(166, 148), 
    'label':'StaticBox4', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(202, 541), 
    'size':(47, 25), 
    'label':'Plot', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(20, 138), 
    'size':(261, -1), 
    'layout':'horizontal', 
    },

{'type':'Slider', 
    'name':'ImageMax', 
    'position':(574, 624), 
    'size':(104, 18), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'MultiColumnList', 
    'name':'MultiColumnList1Copy', 
    'position':(349, 275), 
    'size':(340, 239), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'MultiColumnList', 
    'name':'IntParamList', 
    'position':(14, 278), 
    'size':(315, 236), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(294, 56), 
    'size':(2, 152), 
    'layout':'horizontal', 
    },

{'type':'TextArea', 
    'name':'PointData', 
    'position':(491, 54), 
    'size':(201, 155), 
    'text':'Data Point Information\n', 
    },

{'type':'Button', 
    'name':'NextPoint', 
    'position':(121, 71), 
    'size':(22, 25), 
    'label':'>', 
    },

{'type':'Button', 
    'name':'PrevPoint', 
    'position':(21, 71), 
    'size':(23, 24), 
    'label':'<', 
    },

{'type':'StaticText', 
    'name':'colormap', 
    'position':(598, 539), 
    'text':'colormap', 
    },

{'type':'Choice', 
    'name':'ColorMap', 
    'position':(574, 562), 
    'size':(105, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(487, 38), 
    'size':(210, 175), 
    },

{'type':'Button', 
    'name':'AppendScan', 
    'position':(342, 7), 
    'size':(94, 22), 
    'label':'Append Scan', 
    },

{'type':'TextField', 
    'name':'IntParam', 
    'position':(79, 246), 
    'size':(248, 27), 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(31, 142), 
    'text':'On point / set selection:', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(11, 5), 
    'size':(67, 24), 
    'label':'Update', 
    },

{'type':'StaticText', 
    'name':'Lbl1', 
    'position':(85, 10), 
    'text':'Ctr Data Name', 
    },

{'type':'ComboBox', 
    'name':'CtrData', 
    'position':(177, 7), 
    'size':(139, -1), 
    'items':[u''], 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(11, 37), 
    'size':(472, 176), 
    'label':'Data point', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(56, 56), 
    'text':'Point Num', 
    },

{'type':'ComboBox', 
    'name':'PointNum', 
    'position':(49, 72), 
    'size':(69, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'CheckBox', 
    'name':'SetScanIntParams', 
    'position':(20, 164), 
    'size':(150, 20), 
    'label':'Set integration params', 
    },

{'type':'CheckBox', 
    'name':'SetCorrectionParmeters', 
    'position':(20, 188), 
    'size':(149, -1), 
    'label':'Set correction params', 
    },

{'type':'Button', 
    'name':'SetPointClick', 
    'position':(191, 77), 
    'size':(74, 25), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(203, 142), 
    'text':'From point:', 
    },

{'type':'ComboBox', 
    'name':'AnchorPointNum', 
    'position':(202, 173), 
    'size':(75, -1), 
    'items':[u''], 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(33, 622), 
    'size':(72, 15), 
    'checked':True, 
    'label':'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoIntegrate', 
    'position':(175, 113), 
    'size':(109, -1), 
    'checked':True, 
    'label':'Auto Integrate', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(342, 221), 
    'size':(355, 299), 
    'label':'Correction Parameters', 
    },

{'type':'StaticText', 
    'name':'lbl4', 
    'position':(176, 57), 
    'text':'Set point from plot', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'MedPath', 
    'position':(305, 69), 
    'size':(168, 99), 
    },

{'type':'Button', 
    'name':'MedPathSel', 
    'position':(414, 182), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl1001', 
    'position':(314, 52), 
    'text':'New / selected point set', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'StaticText', 
    'name':'lbl005', 
    'position':(311, 176), 
    'size':(95, 31), 
    'text':'Select set from plot zoom', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'CorrParam', 
    'position':(410, 243), 
    'size':(278, -1), 
    },

{'type':'StaticText', 
    'name':'ImaxLbl', 
    'position':(480, 601), 
    'text':'Image Max =', 
    },

{'type':'TextField', 
    'name':'Imax', 
    'position':(574, 594), 
    'text':'-1', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(8, 222), 
    'size':(328, 298), 
    'label':'Integration Parameters', 
    },

{'type':'Button', 
    'name':'FitDeadtime', 
    'position':(20, 106), 
    'size':(132, -1), 
    'label':'Integrate / Update', 
    },

{'type':'StaticText', 
    'name':'StaticText321', 
    'position':(22, 250), 
    'text':'Param=', 
    },

{'type':'Choice', 
    'name':'AppendScanSelect', 
    'position':(457, 6), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(183, 521), 
    'size':(270, 147), 
    'label':'Plot Rocking Scan', 
    },

{'type':'Button', 
    'name':'PlotCtr', 
    'position':(31, 545), 
    'size':(71, 27), 
    'label':'CTR Plot ', 
    },

{'type':'CheckBox', 
    'name':'CtrPlotInt', 
    'position':(32, 589), 
    'size':(120, -1), 
    'label':'Plot as intensities', 
    },

{'type':'StaticBox', 
    'name':'box', 
    'position':(460, 523), 
    'size':(239, 146), 
    'label':'Plot Image', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(356, 246), 
    'text':'Param=', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(225, 582), 
    'text':'X=', 
    },

{'type':'Choice', 
    'name':'XPlot', 
    'position':(255, 578), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(274, 547), 
    'size':(45, -1), 
    'label':'Xlog', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(226, 611), 
    'text':'Y=', 
    },

{'type':'Choice', 
    'name':'YPlot', 
    'position':(255, 607), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(333, 545), 
    'label':'Ylog', 
    },

{'type':'StaticText', 
    'name':'StaticText311', 
    'position':(202, 640), 
    'text':'Norm=', 
    },

{'type':'Choice', 
    'name':'NormPlot', 
    'position':(255, 636), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(394, 546), 
    'label':'Hold', 
    },

{'type':'Button', 
    'name':'PlotImg', 
    'position':(475, 557), 
    'size':(73, -1), 
    'label':'Plot Image', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(10, 675), 
    'size':(695, 6), 
    'layout':'horizontal', 
    },

] # end components
} # end background
] # end backgrounds
} }
