{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxCtr_bgTemplate',
          'title':u'Ctr Data',
          'size':(716, 866),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadCtr',
                   'label':u'ReadCtrFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveCtr',
                   'label':u'SaveCtr',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileWriteHKL',
                   'label':u'WriteHKL',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'&Help',
             'items': [
              ]
             },
         ]
     },
         'components': [

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(15, 664), 
    'text':u'Num Columns', 
    },

{'type':'TextField', 
    'name':'PlotCol', 
    'position':(105, 660), 
    'size':(26, 25), 
    'text':u'2', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(141, 662), 
    'size':(136, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(622, 231), 
    'size':(68, 49), 
    'text':u'Copy these parameters to all points', 
    },

{'type':'Button', 
    'name':'CopyParamsToAll', 
    'position':(622, 282), 
    'size':(63, 29), 
    'label':u'Copy All', 
    },

{'type':'TextField', 
    'name':'ParamName', 
    'position':(72, 323), 
    'size':(120, 26), 
    'editable':False, 
    },

{'type':'TextArea', 
    'name':'ParamDescr', 
    'position':(16, 233), 
    'size':(598, 85), 
    'editable':False, 
    'text':u'Parameter Description', 
    },

{'type':'StaticBox', 
    'name':'StaticBox6', 
    'position':(10, 212), 
    'size':(689, 146), 
    'label':u'Parameters', 
    },

{'type':'Button', 
    'name':'SetUpdate', 
    'position':(250, 84), 
    'size':(42, 21), 
    'label':u'Set', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(102, 86), 
    'text':u'Integrate/update', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(153, 594), 
    'size':(131, 26), 
    'text':u'Raw scan data (Fig 1)', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(140, 591), 
    'size':(2, 122), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotScan', 
    'position':(201, 620), 
    'size':(73, 19), 
    'label':u'Auto Plot', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(151, 667), 
    'text':u'Correction Plot (Fig 2)', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(20, 592), 
    'text':u'Ctr Plot (Fig 0)', 
    },

{'type':'Button', 
    'name':'CorrPlot', 
    'position':(152, 685), 
    'size':(38, 27), 
    'label':u'Plot', 
    },

{'type':'Button', 
    'name':'ParamSet', 
    'position':(15, 322), 
    'size':(48, 27), 
    'label':u'Set', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(177, 169), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':u'>', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotIntegration', 
    'position':(145, 140), 
    'size':(149, -1), 
    'label':u'Plot Integration (Fig 3)', 
    },

{'type':'Choice', 
    'name':'AnchorPointNum', 
    'position':(201, 178), 
    'size':(81, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(19, 737), 
    'text':u'Add: select plane group and calculate / plot averages.  Under file we need to read / write ctr files (as hdf)', 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(312, 31), 
    'size':(386, 183), 
    'label':u'Info', 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(9, 574), 
    'size':(275, 147), 
    'label':u'Data Plots', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(17, 115), 
    'size':(271, -1), 
    'layout':'horizontal', 
    },

{'type':'Slider', 
    'name':'ImaxSlider', 
    'position':(299, 699), 
    'size':(104, 18), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':100, 
    },

{'type':'MultiColumnList', 
    'name':'CorrParamList', 
    'position':(348, 382), 
    'size':(343, 183), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'MultiColumnList', 
    'name':'IntParamList', 
    'position':(15, 381), 
    'size':(316, 184), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'TextArea', 
    'name':'PointData', 
    'position':(320, 55), 
    'size':(374, 152), 
    'editable':False, 
    'text':u'Data Point Information\n', 
    },

{'type':'Button', 
    'name':'NextPoint', 
    'position':(53, 88), 
    'size':(36, 19), 
    'label':u'>', 
    },

{'type':'Button', 
    'name':'PrevPoint', 
    'position':(19, 88), 
    'size':(35, 19), 
    'label':u'<', 
    },

{'type':'StaticText', 
    'name':'colormap', 
    'position':(317, 594), 
    'text':u'colormap', 
    },

{'type':'Choice', 
    'name':'ColorMap', 
    'position':(299, 615), 
    'size':(105, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'AppendScan', 
    'position':(420, 6), 
    'size':(94, 21), 
    'label':u'Append Scan', 
    },

{'type':'TextField', 
    'name':'ParamVal', 
    'position':(197, 322), 
    'size':(495, 27), 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(21, 118), 
    'size':(217, -1), 
    'text':u'On point / set selection or append:', 
    'toolTip':u'Provide Tdl variable hodling values', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(7, 4), 
    'size':(147, 22), 
    'label':u'Update Shell Variables', 
    },

{'type':'StaticText', 
    'name':'Lbl1', 
    'position':(168, 8), 
    'text':u'Ctr Data Name', 
    },

{'type':'ComboBox', 
    'name':'CtrDataVar', 
    'position':(262, 5), 
    'size':(139, -1), 
    'items':[u''], 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(9, 30), 
    'size':(297, 184), 
    'label':u'Data point', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(26, 47), 
    'text':u'Point Index', 
    },

{'type':'ComboBox', 
    'name':'PointNum', 
    'position':(21, 64), 
    'size':(69, -1), 
    'items':[u'0'], 
    'stringSelection':u'0', 
    'text':u'0', 
    },

{'type':'CheckBox', 
    'name':'SetIntParams', 
    'position':(22, 163), 
    'size':(150, 20), 
    'label':u'Set integration params', 
    },

{'type':'CheckBox', 
    'name':'SetCorrParams', 
    'position':(22, 189), 
    'size':(149, -1), 
    'label':u'Set correction params', 
    },

{'type':'Button', 
    'name':'SetPointClick', 
    'position':(204, 57), 
    'size':(42, 21), 
    'label':u'Point', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(204, 160), 
    'text':u'Anchor  index:', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCtr', 
    'position':(65, 613), 
    'size':(72, 15), 
    'checked':True, 
    'label':u'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoIntegrate', 
    'position':(22, 140), 
    'size':(109, -1), 
    'checked':True, 
    'label':u'Auto Integrate', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(342, 359), 
    'size':(355, 213), 
    'label':u'Correction Parameters', 
    },

{'type':'StaticText', 
    'name':'lbl4', 
    'position':(103, 59), 
    'size':(93, -1), 
    'text':u'Select from plot', 
    'toolTip':u'Provide Tdl variable hodling values', 
    },

{'type':'Button', 
    'name':'SetPointsClick', 
    'position':(250, 57), 
    'size':(42, 21), 
    'label':u'Set ', 
    },

{'type':'StaticText', 
    'name':'ImaxLbl', 
    'position':(309, 646), 
    'text':u'Image Max =', 
    },

{'type':'TextField', 
    'name':'Imax', 
    'position':(300, 667), 
    'text':u'-1', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(8, 359), 
    'size':(328, 213), 
    'label':u'Integration Parameters', 
    },

{'type':'Button', 
    'name':'PointUpdate', 
    'position':(204, 84), 
    'size':(42, 21), 
    'label':u'Point', 
    },

{'type':'Choice', 
    'name':'AppendScanVar', 
    'position':(535, 4), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(423, 572), 
    'size':(274, 147), 
    'label':u'Rocking Scan Plot Params', 
    },

{'type':'Button', 
    'name':'PlotCtr', 
    'position':(16, 614), 
    'size':(40, -1), 
    'label':u'Plot ', 
    },

{'type':'CheckBox', 
    'name':'CtrPlotInt', 
    'position':(65, 633), 
    'size':(70, -1), 
    'label':u'Intensity', 
    },

{'type':'StaticBox', 
    'name':'box', 
    'position':(288, 572), 
    'size':(130, 146), 
    'label':u'Image Plot Params', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(456, 636), 
    'text':u'X=', 
    },

{'type':'Choice', 
    'name':'XPlot', 
    'position':(486, 632), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(505, 601), 
    'size':(45, -1), 
    'label':u'Xlog', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(457, 665), 
    'text':u'Y=', 
    },

{'type':'Choice', 
    'name':'YPlot', 
    'position':(486, 661), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(564, 599), 
    'label':u'Ylog', 
    },

{'type':'StaticText', 
    'name':'StaticText311', 
    'position':(433, 694), 
    'text':u'Norm=', 
    },

{'type':'Choice', 
    'name':'NormPlot', 
    'position':(486, 690), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(625, 600), 
    'label':u'Hold', 
    },

{'type':'Button', 
    'name':'PlotScanData', 
    'position':(153, 618), 
    'size':(39, 26), 
    'label':u'Plot', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(9, 762), 
    'size':(691, 6), 
    'layout':'horizontal', 
    },

] # end components
} # end background
] # end backgrounds
} }
