{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':'Standard Template with File->Exit menu',
          'size':(1151, 614),
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'CheckBox', 
    'name':'AxisIgnore', 
    'position':(20, 374), 
    'label':'Ignore', 
    },

{'type':'StaticText', 
    'name':'LegendLoclbl', 
    'position':(826, 370), 
    'text':'Location', 
    },

{'type':'ComboBox', 
    'name':'LegendLoc', 
    'position':(876, 366), 
    'size':(93, -1), 
    'items':[u'0', u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10'], 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(991, 350), 
    'size':(5, 137), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Ymaxlbl', 
    'position':(356, 351), 
    'text':'Y Max', 
    },

{'type':'StaticText', 
    'name':'Yminlbl', 
    'position':(286, 351), 
    'text':'Y Min', 
    },

{'type':'StaticText', 
    'name':'Xmaxlbl', 
    'position':(218, 351), 
    'text':'X Max', 
    },

{'type':'StaticText', 
    'name':'Xminlbl', 
    'position':(149, 351), 
    'text':'X Min', 
    },

{'type':'TextField', 
    'name':'Ymax', 
    'position':(339, 367), 
    'size':(64, -1), 
    },

{'type':'TextField', 
    'name':'Ymin', 
    'position':(270, 367), 
    'size':(57, -1), 
    },

{'type':'TextField', 
    'name':'Xmax', 
    'position':(203, 367), 
    'size':(57, -1), 
    },

{'type':'TextField', 
    'name':'Xmin', 
    'position':(133, 367), 
    'size':(58, -1), 
    },

{'type':'CheckBox', 
    'name':'Ycen', 
    'position':(550, 79), 
    'label':'Y Center', 
    },

{'type':'CheckBox', 
    'name':'Xcen', 
    'position':(550, 48), 
    'label':'X Center', 
    },

{'type':'Button', 
    'name':'DeleteAxis', 
    'position':(16, 349), 
    'size':(52, 21), 
    'label':'Delete', 
    },

{'type':'MultiColumnList', 
    'name':'AxisParams', 
    'position':(8, 392), 
    'size':(978, 95), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Num', 'Xmin', 'Xmax', 'Ymin', 'Ymax', 'Xlog', 'Ylog', 'X Title', 'Y Title', 'Plot Title', 'Legend', 'Legend Loc', 'Ignore'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'CheckBox', 
    'name':'ShowLegend', 
    'position':(890, 351), 
    'label':'Legend', 
    },

{'type':'StaticText', 
    'name':'PlotTitlelbl', 
    'position':(728, 351), 
    'text':'Plot Title', 
    },

{'type':'TextField', 
    'name':'PlotTitle', 
    'position':(687, 367), 
    'size':(126, -1), 
    },

{'type':'StaticText', 
    'name':'Ytitlelbl', 
    'position':(604, 351), 
    'text':'Y Title', 
    },

{'type':'TextField', 
    'name':'Ytitle', 
    'position':(576, 366), 
    },

{'type':'StaticText', 
    'name':'Xtitlelbl', 
    'position':(512, 351), 
    'text':'X Title', 
    },

{'type':'TextField', 
    'name':'Xtitle', 
    'position':(468, 367), 
    },

{'type':'StaticText', 
    'name':'PlotNum_2lbl', 
    'position':(86, 351), 
    'text':'Plot Num', 
    },

{'type':'TextField', 
    'name':'PlotNum_axis', 
    'position':(83, 365), 
    'size':(38, -1), 
    'text':'1', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(10, 345), 
    'size':(1122, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Ylbl', 
    'position':(203, 82), 
    'text':'Y', 
    },

{'type':'ComboBox', 
    'name':'Y', 
    'position':(218, 78), 
    'size':(147, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Yerrlbl', 
    'position':(376, 82), 
    'text':'Yerr', 
    },

{'type':'ComboBox', 
    'name':'Yerr', 
    'position':(398, 78), 
    'size':(141, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Yscalelbl', 
    'position':(617, 80), 
    'text':'Yscale', 
    },

{'type':'TextField', 
    'name':'Yscale', 
    'position':(654, 74), 
    'size':(49, -1), 
    'text':'1', 
    },

{'type':'CheckBox', 
    'name':'Ynorm', 
    'position':(711, 78), 
    'label':'Normalize to scale', 
    },

{'type':'StaticText', 
    'name':'Yoffsetlbl', 
    'position':(829, 78), 
    'text':'Yoffset', 
    },

{'type':'TextField', 
    'name':'Yoff', 
    'position':(873, 74), 
    'size':(67, -1), 
    'text':'0', 
    },

{'type':'CheckBox', 
    'name':'Ylog', 
    'position':(420, 373), 
    'size':(40, -1), 
    'label':'Ylog', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(954, 38), 
    'size':(4, 73), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(191, 39), 
    'size':(4, 71), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Description 4', 
    'position':(1002, 464), 
    'text':'Yerr_plot = Yerr*scale', 
    },

{'type':'StaticText', 
    'name':'Description 3', 
    'position':(1001, 429), 
    'text':'Xerr_plot = Xerr*scale', 
    },

{'type':'TextArea', 
    'name':'PrintCmds', 
    'position':(8, 489), 
    'size':(1124, 52), 
    'editable':False, 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'StaticText', 
    'name':'Symbollbl', 
    'position':(1092, 39), 
    'text':'Symbol', 
    },

{'type':'StaticText', 
    'name':'Linelbl', 
    'position':(1045, 40), 
    'text':'Line', 
    },

{'type':'ComboBox', 
    'name':'Symbol', 
    'position':(1084, 55), 
    'size':(50, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Line', 
    'position':(1031, 55), 
    'size':(48, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'KwArgslbl', 
    'position':(965, 88), 
    'text':'KW', 
    },

{'type':'TextField', 
    'name':'KwArgs', 
    'position':(986, 83), 
    'size':(150, -1), 
    },

{'type':'StaticText', 
    'name':'PlotNumlbl', 
    'position':(14, 79), 
    'text':'Plot Num', 
    },

{'type':'StaticText', 
    'name':'Ncollbl', 
    'position':(297, 13), 
    'text':'Num Plot Cols', 
    },

{'type':'StaticText', 
    'name':'Nrowlbl', 
    'position':(154, 11), 
    'text':'Num Plot Rows', 
    },

{'type':'CheckBox', 
    'name':'Ignore', 
    'position':(129, 91), 
    'label':'Ignore', 
    },

{'type':'TextField', 
    'name':'PlotNum', 
    'position':(67, 77), 
    'size':(37, -1), 
    'text':'1', 
    },

{'type':'TextField', 
    'name':'Ncol', 
    'position':(379, 8), 
    'size':(45, -1), 
    'text':'1', 
    },

{'type':'TextField', 
    'name':'Nrow', 
    'position':(241, 8), 
    'size':(40, -1), 
    'text':'1', 
    },

{'type':'Button', 
    'name':'Delete', 
    'position':(129, 65), 
    'size':(48, 20), 
    'label':'Delete', 
    },

{'type':'ComboBox', 
    'name':'Color', 
    'position':(972, 55), 
    'size':(49, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'SaveName', 
    'position':(1008, 382), 
    'size':(122, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'UpdateTdl', 
    'position':(76, 5), 
    'size':(54, -1), 
    'label':'Update', 
    },

{'type':'StaticText', 
    'name':'Labellbl', 
    'position':(12, 45), 
    'text':'Plot Label', 
    },

{'type':'TextField', 
    'name':'Label', 
    'position':(68, 42), 
    'size':(114, -1), 
    'text':'Plot 1', 
    },

{'type':'StaticText', 
    'name':'Ydescription1', 
    'position':(1000, 446), 
    'text':'Yplot = (Y*scale+ Yoffset)', 
    },

{'type':'StaticText', 
    'name':'Description1', 
    'position':(998, 412), 
    'text':'Xplot = (X*scale + Xoffset) ', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(9, 35), 
    'size':(1116, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(11, 4), 
    'size':(51, 24), 
    'label':'Plot', 
    },

{'type':'Button', 
    'name':'Load', 
    'position':(1079, 354), 
    'size':(55, -1), 
    'label':'Load', 
    },

{'type':'Button', 
    'name':'Save', 
    'position':(1017, 355), 
    'size':(55, -1), 
    'label':'Save', 
    },

{'type':'StaticText', 
    'name':'Fmtlbl', 
    'position':(980, 40), 
    'text':'Color', 
    },

{'type':'StaticText', 
    'name':'Xlbl', 
    'position':(203, 48), 
    'text':'X', 
    },

{'type':'ComboBox', 
    'name':'X', 
    'position':(218, 44), 
    'size':(145, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Xerrlbl', 
    'position':(376, 48), 
    'text':'Xerr', 
    },

{'type':'ComboBox', 
    'name':'Xerr', 
    'position':(399, 44), 
    'size':(141, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Xscalelbl', 
    'position':(616, 47), 
    'text':'Xscale', 
    },

{'type':'TextField', 
    'name':'Xscale', 
    'position':(654, 42), 
    'size':(49, -1), 
    'text':'1', 
    },

{'type':'CheckBox', 
    'name':'Xnorm', 
    'position':(711, 48), 
    'label':'Normalize to scale', 
    },

{'type':'StaticText', 
    'name':'Xofflbl', 
    'position':(828, 48), 
    'text':'Xoffset', 
    },

{'type':'TextField', 
    'name':'Xoff', 
    'position':(871, 44), 
    'size':(67, -1), 
    'text':'0', 
    },

{'type':'CheckBox', 
    'name':'Xlog', 
    'position':(420, 353), 
    'size':(41, -1), 
    'label':'Xlog', 
    },

{'type':'MultiColumnList', 
    'name':'PlotParams', 
    'position':(7, 109), 
    'size':(1130, 234), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Label', 'Num', 'X', 'Y', 'Xerr', 'Yerr', 'Xcen', 'Ycen', 'Xscale', 'Yscale', 'Xnorm', 'Ynorm', 'Xoff', 'Yoff', 'Color', 'Line', 'Symbol', 'KW', 'Ignore'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

] # end components
} # end background
] # end backgrounds
} }
