{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':'Plot Selection',
          'size':(993, 590),
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Choice', 
    'name':'PlotNum_axis', 
    'position':(77, 322), 
    'size':(55, -1), 
    'items':[u'1'], 
    'stringSelection':'1', 
    },

{'type':'Choice', 
    'name':'PlotNum', 
    'position':(64, 75), 
    'size':(54, -1), 
    'items':[u'1'], 
    'stringSelection':'1', 
    },

{'type':'CheckBox', 
    'name':'AxisIgnore', 
    'position':(15, 329), 
    'label':'Ignore', 
    },

{'type':'StaticText', 
    'name':'LegendLoclbl', 
    'position':(828, 326), 
    'text':'Location', 
    },

{'type':'ComboBox', 
    'name':'LegendLoc', 
    'position':(878, 322), 
    'size':(93, -1), 
    'items':[u'0', u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10'], 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(13, 514), 
    'size':(965, 4), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Ymaxlbl', 
    'position':(358, 307), 
    'text':'Y Max', 
    },

{'type':'StaticText', 
    'name':'Yminlbl', 
    'position':(288, 307), 
    'text':'Y Min', 
    },

{'type':'StaticText', 
    'name':'Xmaxlbl', 
    'position':(220, 307), 
    'text':'X Max', 
    },

{'type':'StaticText', 
    'name':'Xminlbl', 
    'position':(151, 307), 
    'text':'X Min', 
    },

{'type':'TextField', 
    'name':'Ymax', 
    'position':(341, 323), 
    'size':(64, -1), 
    },

{'type':'TextField', 
    'name':'Ymin', 
    'position':(272, 323), 
    'size':(57, -1), 
    },

{'type':'TextField', 
    'name':'Xmax', 
    'position':(205, 323), 
    'size':(57, -1), 
    },

{'type':'TextField', 
    'name':'Xmin', 
    'position':(135, 323), 
    'size':(58, -1), 
    },

{'type':'CheckBox', 
    'name':'Ycen', 
    'position':(570, 82), 
    'label':'Y Center', 
    },

{'type':'CheckBox', 
    'name':'Xcen', 
    'position':(570, 48), 
    'label':'X Center', 
    },

{'type':'Button', 
    'name':'DeleteAxis', 
    'position':(12, 305), 
    'size':(52, 21), 
    'label':'Delete', 
    },

{'type':'MultiColumnList', 
    'name':'AxisParams', 
    'position':(12, 350), 
    'size':(963, 95), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Num', 'Xmin', 'Xmax', 'Ymin', 'Ymax', 'Xlog', 'Ylog', 'X Title', 'Y Title', 'Plot Title', 'Legend', 'Legend Loc', 'Ignore'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'CheckBox', 
    'name':'ShowLegend', 
    'position':(892, 307), 
    'label':'Legend', 
    },

{'type':'StaticText', 
    'name':'PlotTitlelbl', 
    'position':(730, 307), 
    'text':'Plot Title', 
    },

{'type':'TextField', 
    'name':'PlotTitle', 
    'position':(689, 323), 
    'size':(126, -1), 
    },

{'type':'StaticText', 
    'name':'Ytitlelbl', 
    'position':(606, 307), 
    'text':'Y Title', 
    },

{'type':'TextField', 
    'name':'Ytitle', 
    'position':(578, 322), 
    },

{'type':'StaticText', 
    'name':'Xtitlelbl', 
    'position':(514, 307), 
    'text':'X Title', 
    },

{'type':'TextField', 
    'name':'Xtitle', 
    'position':(470, 323), 
    },

{'type':'StaticText', 
    'name':'PlotNum_2lbl', 
    'position':(84, 307), 
    'text':'Plot Num', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(10, 298), 
    'size':(970, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Ylbl', 
    'position':(203, 82), 
    'text':'Y', 
    },

{'type':'ComboBox', 
    'name':'Y', 
    'position':(218, 77), 
    'size':(164, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Yerrlbl', 
    'position':(396, 81), 
    'text':'Yerr', 
    },

{'type':'ComboBox', 
    'name':'Yerr', 
    'position':(418, 77), 
    'size':(141, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Yscalelbl', 
    'position':(637, 82), 
    'text':'Yscale', 
    },

{'type':'TextField', 
    'name':'Yscale', 
    'position':(674, 78), 
    'size':(49, -1), 
    'text':'1', 
    },

{'type':'CheckBox', 
    'name':'Ynorm', 
    'position':(731, 82), 
    'label':'Normalize to scale', 
    },

{'type':'StaticText', 
    'name':'Yoffsetlbl', 
    'position':(849, 82), 
    'text':'Yoffset', 
    },

{'type':'TextField', 
    'name':'Yoff', 
    'position':(893, 78), 
    'size':(67, -1), 
    'text':'0', 
    },

{'type':'CheckBox', 
    'name':'Ylog', 
    'position':(422, 329), 
    'size':(40, -1), 
    'label':'Ylog', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(469, -11), 
    'size':(4, 45), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(191, 39), 
    'size':(4, 92), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'Description 4', 
    'position':(417, 525), 
    'text':'Yerr_plot = Yerr*scale', 
    },

{'type':'StaticText', 
    'name':'Description 3', 
    'position':(156, 523), 
    'text':'Xerr_plot = Xerr*scale', 
    },

{'type':'TextArea', 
    'name':'PrintCmds', 
    'position':(12, 451), 
    'size':(965, 52), 
    'editable':False, 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'StaticText', 
    'name':'Symbollbl', 
    'position':(392, 113), 
    'text':'Symbol', 
    },

{'type':'StaticText', 
    'name':'Linelbl', 
    'position':(304, 114), 
    'text':'Line', 
    },

{'type':'ComboBox', 
    'name':'Symbol', 
    'position':(430, 110), 
    'size':(57, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Line', 
    'position':(326, 110), 
    'size':(56, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'KwArgslbl', 
    'position':(501, 114), 
    'text':'KW', 
    },

{'type':'TextField', 
    'name':'KwArgs', 
    'position':(527, 110), 
    'size':(172, -1), 
    },

{'type':'StaticText', 
    'name':'PlotNumlbl', 
    'position':(11, 79), 
    'text':'Plot Num', 
    },

{'type':'StaticText', 
    'name':'Ncollbl', 
    'position':(297, 11), 
    'text':'Num Plot Cols', 
    },

{'type':'StaticText', 
    'name':'Nrowlbl', 
    'position':(154, 11), 
    'text':'Num Plot Rows', 
    },

{'type':'CheckBox', 
    'name':'Ignore', 
    'position':(63, 107), 
    'label':'Ignore', 
    },

{'type':'TextField', 
    'name':'Ncol', 
    'position':(379, 7), 
    'size':(45, -1), 
    'text':'1', 
    },

{'type':'TextField', 
    'name':'Nrow', 
    'position':(241, 7), 
    'size':(40, -1), 
    'text':'1', 
    },

{'type':'Button', 
    'name':'Delete', 
    'position':(131, 74), 
    'size':(48, -1), 
    'label':'Delete', 
    },

{'type':'ComboBox', 
    'name':'Color', 
    'position':(239, 109), 
    'size':(58, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'SaveName', 
    'position':(641, 7), 
    'size':(155, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'UpdateTdl', 
    'position':(76, 6), 
    'size':(54, -1), 
    'label':'Update', 
    },

{'type':'StaticText', 
    'name':'Labellbl', 
    'position':(12, 45), 
    'text':'Plot Label', 
    },

{'type':'TextField', 
    'name':'Label', 
    'position':(65, 42), 
    'size':(117, -1), 
    'text':'Plot 1', 
    },

{'type':'StaticText', 
    'name':'Ydescription1', 
    'position':(277, 525), 
    'text':'Yplot = (Y*scale+ Yoffset)', 
    },

{'type':'StaticText', 
    'name':'Description1', 
    'position':(14, 523), 
    'text':'Xplot = (X*scale + Xoffset) ', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(9, 35), 
    'size':(949, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(11, 6), 
    'size':(51, 24), 
    'label':'Plot', 
    },

{'type':'Button', 
    'name':'Load', 
    'position':(564, 6), 
    'size':(55, -1), 
    'label':'Load', 
    },

{'type':'Button', 
    'name':'Save', 
    'position':(494, 6), 
    'size':(55, -1), 
    'label':'Save', 
    },

{'type':'StaticText', 
    'name':'Fmtlbl', 
    'position':(210, 113), 
    'text':'Color', 
    },

{'type':'StaticText', 
    'name':'Xlbl', 
    'position':(203, 48), 
    'text':'X', 
    },

{'type':'ComboBox', 
    'name':'X', 
    'position':(218, 44), 
    'size':(164, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Xerrlbl', 
    'position':(396, 47), 
    'text':'Xerr', 
    },

{'type':'ComboBox', 
    'name':'Xerr', 
    'position':(419, 43), 
    'size':(141, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Xscalelbl', 
    'position':(636, 48), 
    'text':'Xscale', 
    },

{'type':'TextField', 
    'name':'Xscale', 
    'position':(674, 44), 
    'size':(49, -1), 
    'text':'1', 
    },

{'type':'CheckBox', 
    'name':'Xnorm', 
    'position':(731, 48), 
    'label':'Normalize to scale', 
    },

{'type':'StaticText', 
    'name':'Xofflbl', 
    'position':(848, 48), 
    'text':'Xoffset', 
    },

{'type':'TextField', 
    'name':'Xoff', 
    'position':(891, 44), 
    'size':(67, -1), 
    'text':'0', 
    },

{'type':'CheckBox', 
    'name':'Xlog', 
    'position':(422, 309), 
    'size':(41, -1), 
    'label':'Xlog', 
    },

{'type':'MultiColumnList', 
    'name':'PlotParams', 
    'position':(10, 143), 
    'size':(970, 147), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Label', 'Num', 'X', 'Y', 'Xerr', 'Yerr', 'Xcen', 'Ycen', 'Xscale', 'Yscale', 'Xnorm', 'Ynorm', 'Xoff', 'Yoff', 'Color', 'Line', 'Symbol', 'KW', 'Ignore'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

] # end components
} # end background
] # end backgrounds
} }
