{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'Spec Data',
          'size':(582, 733),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(9, 420), 
    'size':(552, 56), 
    'label':'Scan Variable', 
    },

{'type':'Button', 
    'name':'ImgPathSel', 
    'position':(509, 360), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'TextField', 
    'name':'ImagePath', 
    'position':(93, 359), 
    'size':(400, -1), 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(19, 363), 
    'text':'Image Path', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(16, 7), 
    'size':(56, 22), 
    'label':'Update', 
    },

{'type':'StaticText', 
    'name':'Lbl1', 
    'position':(86, 11), 
    'text':'ReaderGroup', 
    },

{'type':'ComboBox', 
    'name':'Grp', 
    'position':(168, 7), 
    'size':(141, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'Lbl2', 
    'position':(315, 11), 
    'text':'ReaderName', 
    },

{'type':'ComboBox', 
    'name':'Reader', 
    'position':(398, 7), 
    'size':(155, -1), 
    'items':[u'reader'], 
    'stringSelection':'reader', 
    'text':'reader', 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(5, 35), 
    'size':(557, 120), 
    'label':'Spec File', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(20, 63), 
    'text':'Spec Path', 
    },

{'type':'TextField', 
    'name':'SpecPath', 
    'position':(91, 60), 
    'size':(400, -1), 
    },

{'type':'Button', 
    'name':'SpecPathSel', 
    'position':(499, 60), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl111', 
    'position':(19, 95), 
    'text':'Spec File(s)', 
    },

{'type':'Choice', 
    'name':'SpecFile', 
    'position':(91, 91), 
    'size':(273, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'SpecFileSel', 
    'position':(374, 91), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(20, 126), 
    'text':'Scan Num', 
    },

{'type':'ComboBox', 
    'name':'ScanNum', 
    'position':(91, 122), 
    'size':(78, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'ReadMed', 
    'position':(182, 124), 
    'size':(78, 20), 
    'label':'Read Med', 
    },

{'type':'CheckBox', 
    'name':'ReadXrf', 
    'position':(276, 126), 
    'label':'Read XRF', 
    },

{'type':'CheckBox', 
    'name':'ReadImg', 
    'position':(369, 126), 
    'size':(89, -1), 
    'label':'Read Image', 
    },

{'type':'Button', 
    'name':'Read', 
    'position':(469, 121), 
    'size':(46, 25), 
    'label':'Read', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(18, 441), 
    'text':'Variable Name', 
    },

{'type':'ComboBox', 
    'name':'ScanVar', 
    'position':(118, 437), 
    'size':(186, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(313, 441), 
    'size':(72, 15), 
    'checked':True, 
    'label':'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoCalcVarName', 
    'position':(400, 441), 
    'size':(74, -1), 
    'label':'Auto Calc', 
    },

{'type':'CheckBox', 
    'name':'LongName', 
    'position':(488, 441), 
    'label':'Long', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(7, 158), 
    'size':(559, 175), 
    'label':'MED Params', 
    },

{'type':'StaticText', 
    'name':'medxrfPath', 
    'position':(12, 184), 
    'text':'Med/XRF Path', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'MedPath', 
    'position':(97, 180), 
    'size':(400, -1), 
    },

{'type':'Button', 
    'name':'MedPathSel', 
    'position':(508, 181), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl1001', 
    'position':(18, 232), 
    'text':'XRF Lines =', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'ComboBox', 
    'name':'XrfLines', 
    'position':(99, 226), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'Align', 
    'position':(263, 229), 
    'checked':True, 
    'label':'Align', 
    },

{'type':'CheckBox', 
    'name':'Total', 
    'position':(263, 294), 
    'checked':True, 
    'label':'Total', 
    },

{'type':'StaticText', 
    'name':'McaListLbl', 
    'position':(20, 262), 
    'text':'Bad Mcas =', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'ComboBox', 
    'name':'BadMcas', 
    'position':(99, 260), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'CorrectData', 
    'position':(263, 262), 
    'checked':True, 
    'label':'Correct', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(11, 297), 
    'text':'Emin (keV) =', 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(99, 293), 
    'size':(46, -1), 
    'text':'-1', 
    },

{'type':'StaticText', 
    'name':'TauListLbl', 
    'position':(351, 237), 
    'text':'Taus =', 
    'toolTip':'Provide Tdl variable holding Tau values', 
    },

{'type':'ComboBox', 
    'name':'McaTaus', 
    'position':(402, 233), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(149, 297), 
    'text':'Emax =', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(199, 293), 
    'size':(50, -1), 
    'text':'-1', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(333, 209), 
    'size':(233, 124), 
    'label':'Dead Time', 
    },

{'type':'Button', 
    'name':'FitDeadtime', 
    'position':(338, 277), 
    'size':(33, 39), 
    'label':'Fit', 
    },

{'type':'StaticText', 
    'name':'StaticText32', 
    'position':(398, 273), 
    'size':(20, 15), 
    'text':'X=', 
    },

{'type':'Choice', 
    'name':'DTX', 
    'position':(419, 269), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'StaticText321', 
    'position':(378, 303), 
    'text':'Norm=', 
    },

{'type':'Choice', 
    'name':'DTNorm', 
    'position':(419, 300), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(9, 338), 
    'size':(554, 77), 
    'label':'Image Params', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(10, 477), 
    'size':(309, 157), 
    'label':'Plot Scalers', 
    },

{'type':'Button', 
    'name':'PlotScaler', 
    'position':(24, 499), 
    'size':(41, 31), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'ScalerPlot', 
    'position':(85, 505), 
    'checked':True, 
    'label':'Auto Plot Scalers', 
    },

{'type':'CheckBox', 
    'name':'DefaultScalerAxes', 
    'position':(214, 505), 
    'checked':True, 
    'label':'Default Axes', 
    },

{'type':'StaticBox', 
    'name':'plotMedimage', 
    'position':(325, 479), 
    'size':(239, 155), 
    'label':'Plot Med/Image', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(343, 508), 
    'text':'Scan Point', 
    },

{'type':'ComboBox', 
    'name':'ScanPnt', 
    'position':(418, 505), 
    'size':(61, -1), 
    'items':[], 
    'text':'0', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(47, 542), 
    'text':'X=', 
    },

{'type':'Choice', 
    'name':'XPlot', 
    'position':(70, 538), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(265, 542), 
    'size':(45, -1), 
    'label':'Xlog', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(48, 571), 
    'text':'Y=', 
    },

{'type':'Choice', 
    'name':'YPlot', 
    'position':(70, 567), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(265, 571), 
    'label':'Ylog', 
    },

{'type':'Button', 
    'name':'PlotMed', 
    'position':(340, 546), 
    'size':(76, -1), 
    'label':'Plot Med', 
    },

{'type':'CheckBox', 
    'name':'MedYlog', 
    'position':(438, 552), 
    'label':'Ylog', 
    },

{'type':'CheckBox', 
    'name':'MedHold', 
    'position':(492, 552), 
    'size':(43, -1), 
    'label':'Hold', 
    },

{'type':'StaticText', 
    'name':'StaticText311', 
    'position':(24, 600), 
    'text':'Norm=', 
    },

{'type':'Choice', 
    'name':'NormPlot', 
    'position':(70, 596), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(265, 600), 
    'label':'Hold', 
    },

{'type':'Button', 
    'name':'PlotImg', 
    'position':(340, 586), 
    'size':(76, -1), 
    'label':'Plot Image', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(10, 641), 
    'size':(559, 6), 
    'layout':'horizontal', 
    },

] # end components
} # end background
] # end backgrounds
} }
