{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'XRF',
          'size':(785, 959),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'AddBgr', 
    'position':(45, 290), 
    'size':(62, 23), 
    'label':u'Add', 
    },

{'type':'MultiColumnList', 
    'name':'BgrParams', 
    'position':(30, 320), 
    'size':(720, 100), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Exponent', 'TopWidth', 'BottWidth', 'Tangent', 'Compress', 'FitBgr'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'Button', 
    'name':'UpdateParams', 
    'position':(665, 250), 
    'size':(82, 23), 
    'label':u'Update', 
    },

{'type':'Button', 
    'name':'ClearAll', 
    'position':(575, 250), 
    'size':(77, 23), 
    'label':u'ClearAll', 
    },

{'type':'Button', 
    'name':'ClearDet', 
    'position':(475, 250), 
    'size':(94, 23), 
    'label':u'ClearDetector', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(25, 725), 
    'size':(730, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'CopyAllPkParams', 
    'position':(340, 250), 
    'size':(123, 23), 
    'label':u'CopyToAllDetectors', 
    },

{'type':'ComboBox', 
    'name':'TauVariable', 
    'position':(520, 125), 
    'size':(172, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'McaVariable', 
    'position':(500, 65), 
    'size':(178, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'NumMcas', 
    'position':(440, 20), 
    'text':u'NumMcas = 0', 
    },

{'type':'TextArea', 
    'name':'Messages', 
    'position':(25, 815), 
    'size':(734, 35), 
    'editable':False, 
    'text':u'Messages', 
    },

{'type':'Slider', 
    'name':'PkFWHMSlider', 
    'position':(440, 495), 
    'size':(75, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':11, 
    },

{'type':'Slider', 
    'name':'pkAmpSlider', 
    'position':(345, 495), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'Slider', 
    'name':'pkEnSlider', 
    'position':(250, 495), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':50, 
    'min':-50, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'StaticLine', 
    'name':'StaticLine10', 
    'position':(20, 850), 
    'size':(745, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'XrfLineL', 
    'position':(125, 480), 
    'size':(30, -1), 
    'label':u'L', 
    },

{'type':'CheckBox', 
    'name':'XrfLineK', 
    'position':(90, 480), 
    'label':u'K', 
    },

{'type':'StaticText', 
    'name':'IgnoreLbl', 
    'position':(715, 445), 
    'size':(-1, 19), 
    'text':u'Ignore', 
    },

{'type':'StaticText', 
    'name':'PkLblLbl', 
    'position':(190, 450), 
    'text':u'Label', 
    },

{'type':'TextField', 
    'name':'PkLbl', 
    'position':(165, 470), 
    'size':(76, -1), 
    },

{'type':'Button', 
    'name':'UpdateMenus', 
    'position':(40, 30), 
    'size':(56, 39), 
    'label':u'Update', 
    },

{'type':'StaticLine', 
    'name':'StaticLine9', 
    'position':(20, 810), 
    'size':(744, 6), 
    'layout':'horizontal', 
    },

{'type':'ComboBox', 
    'name':'FitChiExp', 
    'position':(350, 750), 
    'size':(60, -1), 
    'items':[], 
    'text':u'0', 
    },

{'type':'ComboBox', 
    'name':'FitEnFlag', 
    'position':(270, 750), 
    'size':(60, -1), 
    'items':[], 
    'text':u'0', 
    },

{'type':'ComboBox', 
    'name':'FitFWHMFlag', 
    'position':(190, 750), 
    'size':(60, -1), 
    'items':[], 
    'text':u'0', 
    },

{'type':'StaticText', 
    'name':'FitChiExpLbl', 
    'position':(345, 730), 
    'text':u'Chi Exponent', 
    },

{'type':'StaticText', 
    'name':'FitEnergyFlagLbl', 
    'position':(270, 730), 
    'text':u'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FitFWHMFlagLbl', 
    'position':(190, 730), 
    'text':u'FWHM Flag', 
    },

{'type':'Button', 
    'name':'XrfLineDel', 
    'position':(35, 475), 
    'size':(45, 25), 
    'label':u'Delete', 
    },

{'type':'TextField', 
    'name':'PkAmpFactor', 
    'position':(645, 470), 
    'size':(64, -1), 
    },

{'type':'TextField', 
    'name':'PkFwhmFlag', 
    'position':(590, 470), 
    'size':(47, -1), 
    },

{'type':'TextField', 
    'name':'PkEnFlag', 
    'position':(530, 470), 
    'size':(49, -1), 
    },

{'type':'TextField', 
    'name':'PkFWHM', 
    'position':(435, 470), 
    'size':(82, -1), 
    },

{'type':'TextField', 
    'name':'PkAmp', 
    'position':(340, 470), 
    'size':(85, -1), 
    },

{'type':'TextField', 
    'name':'PkEn', 
    'position':(250, 470), 
    'size':(80, -1), 
    },

{'type':'CheckBox', 
    'name':'PkIgnore', 
    'position':(720, 470), 
    'size':(19, 19), 
    'label':u'CheckBox', 
    },

{'type':'StaticText', 
    'name':'AmpFactorLbl', 
    'position':(650, 435), 
    'size':(56, 29), 
    'text':u'Amplitude Factor', 
    },

{'type':'StaticText', 
    'name':'FwhmFlagLbl', 
    'position':(590, 435), 
    'size':(43, 32), 
    'text':u'FWHM Flag', 
    },

{'type':'StaticText', 
    'name':'EFlagLbl', 
    'position':(535, 435), 
    'size':(42, 32), 
    'text':u'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FwhmLbl', 
    'position':(460, 450), 
    'text':u'FWHM', 
    },

{'type':'StaticText', 
    'name':'AmpLbl', 
    'position':(355, 450), 
    'text':u'Amplitude', 
    },

{'type':'StaticText', 
    'name':'EnergyLbl', 
    'position':(270, 450), 
    'text':u'Energy', 
    },

{'type':'CheckBox', 
    'name':'XrfLineShow', 
    'position':(330, 165), 
    'label':u'Show', 
    },

{'type':'Button', 
    'name':'XrfLineAdd', 
    'position':(35, 450), 
    'size':(45, 25), 
    'label':u'Add', 
    },

{'type':'StaticLine', 
    'name':'StaticLine8', 
    'position':(25, 425), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'BgrDefault', 
    'position':(680, 290), 
    'size':(67, 23), 
    'label':u'Default', 
    },

{'type':'StaticLine', 
    'name':'StaticLine7', 
    'position':(30, 275), 
    'size':(716, -1), 
    'layout':'horizontal', 
    },

{'type':'TextField', 
    'name':'BgrCompress', 
    'position':(480, 300), 
    'size':(55, 19), 
    'text':u'4', 
    },

{'type':'TextField', 
    'name':'BgrTangent', 
    'position':(415, 300), 
    'size':(45, 19), 
    'text':u'0', 
    },

{'type':'TextField', 
    'name':'BgrBtmWdth', 
    'position':(320, 300), 
    'size':(75, 19), 
    'text':u'4.0', 
    },

{'type':'TextField', 
    'name':'BgrTopWdth', 
    'position':(240, 300), 
    'size':(70, 19), 
    'text':u'0.0', 
    },

{'type':'TextField', 
    'name':'BgrExp', 
    'position':(155, 300), 
    'size':(75, 19), 
    'text':u'2.0', 
    },

{'type':'StaticText', 
    'name':'FitParamDetLbl', 
    'position':(185, 255), 
    'text':u'Detector=', 
    },

{'type':'Choice', 
    'name':'DetSelect', 
    'position':(255, 250), 
    'size':(70, -1), 
    'items':[u'0'], 
    'stringSelection':u'0', 
    },

{'type':'StaticText', 
    'name':'FittingParamsLbl', 
    'position':(30, 250), 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Fitting Parameters', 
    },

{'type':'StaticText', 
    'name':'BgrCompressLbl', 
    'position':(480, 280), 
    'text':u'Compress', 
    },

{'type':'StaticText', 
    'name':'BgrTangentLbl', 
    'position':(415, 280), 
    'text':u'Tangent', 
    },

{'type':'StaticText', 
    'name':'BgrBtmWidthLbl', 
    'position':(320, 280), 
    'text':u'Bottom Width', 
    },

{'type':'StaticText', 
    'name':'BgrTopWidthLbl', 
    'position':(245, 280), 
    'text':u'Top Width', 
    },

{'type':'StaticText', 
    'name':'BgrExpLbl', 
    'position':(165, 280), 
    'text':u'Exponent', 
    },

{'type':'StaticText', 
    'name':'SetIncIncLabel', 
    'position':(335, 70), 
    'text':u'Step', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(20, 10), 
    'size':(744, 7), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(760, 10), 
    'size':(5, 845), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(420, 10), 
    'size':(5, 232), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(20, 10), 
    'size':(5, 844), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'ComponentsCheck', 
    'position':(305, 215), 
    'size':(90, -1), 
    'label':u'Components', 
    },

{'type':'StaticText', 
    'name':'TauListLbl', 
    'position':(440, 125), 
    'text':u'McaTaus = ', 
    'toolTip':u'Provide Tdl variable holding Tau values', 
    },

{'type':'TextField', 
    'name':'TauList', 
    'position':(435, 155), 
    'size':(310, -1), 
    'text':u'[]', 
    },

{'type':'CheckBox', 
    'name':'Align', 
    'position':(510, 45), 
    'checked':True, 
    'label':u'Align', 
    },

{'type':'CheckBox', 
    'name':'Total', 
    'position':(445, 45), 
    'checked':True, 
    'label':u'Total', 
    },

{'type':'TextField', 
    'name':'McaList', 
    'position':(440, 95), 
    'size':(315, -1), 
    'text':u'[]', 
    },

{'type':'StaticText', 
    'name':'McaListLbl', 
    'position':(440, 70), 
    'text':u'Mcas = ', 
    'toolTip':u'Provide Tdl variable hodling values', 
    },

{'type':'CheckBox', 
    'name':'AutoIncCheck', 
    'position':(45, 90), 
    'size':(50, 20), 
    'label':u'Scan', 
    },

{'type':'StaticText', 
    'name':'AutoIncStopLabel', 
    'position':(190, 70), 
    'text':u'Stop', 
    },

{'type':'StaticText', 
    'name':'AutoIncStartLabel', 
    'position':(125, 70), 
    'text':u'Start', 
    },

{'type':'TextField', 
    'name':'AutoIncStop', 
    'position':(180, 90), 
    'size':(56, -1), 
    'text':u'0', 
    },

{'type':'TextField', 
    'name':'AutoIncStart', 
    'position':(115, 90), 
    'size':(60, -1), 
    'text':u'0', 
    },

{'type':'StaticText', 
    'name':'ExtractLbl', 
    'position':(560, 750), 
    'text':u'Extract', 
    },

{'type':'CheckBox', 
    'name':'YerrCheck', 
    'position':(305, 190), 
    'size':(49, -1), 
    'label':u'Yerr', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(20, 240), 
    'size':(741, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'UsePrevFit', 
    'position':(315, 785), 
    'label':u'Use Prev Fit', 
    },

{'type':'ComboBox', 
    'name':'InitScanIdx', 
    'position':(240, 780), 
    'size':(60, -1), 
    'items':[], 
    'text':u'0', 
    },

{'type':'StaticText', 
    'name':'InitScanIdxLbl', 
    'position':(125, 785), 
    'text':u'Index for scan init', 
    },

{'type':'Button', 
    'name':'UpdateData', 
    'position':(430, 200), 
    'size':(80, 32), 
    'label':u'Update Data', 
    },

{'type':'Button', 
    'name':'FitScan', 
    'position':(45, 775), 
    'size':(57, -1), 
    'label':u'Fit Scan', 
    },

{'type':'Button', 
    'name':'Fit', 
    'position':(115, 745), 
    'size':(57, -1), 
    'label':u'Fit', 
    },

{'type':'MultiColumnList', 
    'name':'PkParams', 
    'position':(30, 510), 
    'size':(727, 209), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Label', 'Energy', 'Amp', 'FWHM', 'E-Flag', 'FWHM-Flag', 'Amp-Factor', 'Ignore', 'Area'], 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 7}, 
    'items':[], 
    'maxColumns':20, 
    'rules':False, 
    },

{'type':'Choice', 
    'name':'XrfLine', 
    'position':(85, 450), 
    'size':(74, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'BgrCheck', 
    'position':(555, 300), 
    'size':(98, -1), 
    'checked':True, 
    'label':u'FitBackground', 
    },

{'type':'Button', 
    'name':'Calc', 
    'position':(45, 745), 
    'size':(57, -1), 
    'label':u'Calc', 
    },

{'type':'StaticText', 
    'name':'XrfLineLbl', 
    'position':(90, 430), 
    'text':u'XRF Line =', 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(115, 215), 
    'size':(55, -1), 
    'label':u'Hold', 
    },

{'type':'CheckBox', 
    'name':'YlogChec', 
    'position':(225, 215), 
    'size':(64, -1), 
    'label':u'Ylog', 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(225, 190), 
    'size':(64, -1), 
    'label':u'Xlog', 
    },

{'type':'Button', 
    'name':'EnRange', 
    'position':(705, 205), 
    'size':(42, 23), 
    'label':u'Select', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(610, 205), 
    'size':(85, -1), 
    'text':u'20.0', 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(610, 185), 
    'text':u'Emax (keV)=', 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(515, 205), 
    'size':(85, -1), 
    'text':u'2.0', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(520, 185), 
    'text':u'Emin (keV)=', 
    },

{'type':'ComboBox', 
    'name':'FitFmt', 
    'position':(115, 160), 
    'size':(202, -1), 
    'items':[u'Fit', u'Fit+Bgr', u'Fit and Bgr'], 
    },

{'type':'ComboBox', 
    'name':'DataFmt', 
    'position':(115, 125), 
    'size':(203, -1), 
    'items':[u'Data', u'Data-Bgr', u'Raw Mcas: All', u'Raw Mcas Included'], 
    'text':u'Data', 
    },

{'type':'Spinner', 
    'name':'NodeInc', 
    'position':(320, 90), 
    'size':(75, -1), 
    'max':10000000, 
    'min':-1000000, 
    'value':0, 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(115, 190), 
    'size':(99, -1), 
    'checked':True, 
    'label':u'Auto Update', 
    },

{'type':'CheckBox', 
    'name':'FitPlotCheck', 
    'position':(45, 160), 
    'size':(39, -1), 
    'label':u'Fit', 
    },

{'type':'CheckBox', 
    'name':'DataPlotCheck', 
    'position':(45, 130), 
    'checked':True, 
    'label':u'Data', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(40, 190), 
    'size':(47, 38), 
    'label':u'Plot', 
    },

{'type':'StaticText', 
    'name':'AutoIncIncLabel', 
    'position':(245, 70), 
    'text':u'Inc', 
    },

{'type':'TextField', 
    'name':'AutoIncInc', 
    'position':(245, 90), 
    'size':(60, -1), 
    'text':u'1', 
    },

{'type':'ComboBox', 
    'name':'NodePfx', 
    'position':(220, 40), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Grp', 
    'position':(105, 40), 
    'size':(110, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'nodeLabel', 
    'position':(285, 20), 
    'text':u'XRF node', 
    },

{'type':'StaticText', 
    'name':'grpLabel', 
    'position':(130, 20), 
    'text':u'XRF group', 
    },

] # end components
} # end background
] # end backgrounds
} }
