{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'XRF',
          'size':(769, 799),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticLine', 
    'name':'StaticLine15', 
    'position':(541, 313), 
    'size':(209, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'ClearParamsLabel', 
    'position':(547, 377), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'text':'Clear All Parameters', 
    },

{'type':'StaticText', 
    'name':'ClearDetLabel', 
    'position':(547, 352), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'text':'Clear Selected Detector', 
    },

{'type':'StaticText', 
    'name':'CopyDetLabel', 
    'position':(547, 324), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'text':'Copy Selected Detector ', 
    },

{'type':'StaticText', 
    'name':'UpdateXrfLabel', 
    'position':(555, 291), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'Update XRF', 
    },

{'type':'StaticLine', 
    'name':'StaticLine14', 
    'position':(393, 13), 
    'size':(3, 83), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'plotParameters', 
    'position':(23, 105), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'text':'Plot Parameters', 
    },

{'type':'StaticLine', 
    'name':'StaticLine13', 
    'position':(14, 96), 
    'size':(736, 6), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine12', 
    'position':(17, 125), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'SetParFromSave', 
    'position':(403, 69), 
    'label':'Set Parameters From Save On Read', 
    },

{'type':'Button', 
    'name':'RestoreSavePar', 
    'position':(672, 65), 
    'size':(53, 22), 
    'label':'Restore', 
    },

{'type':'Button', 
    'name':'SaveSavePar', 
    'position':(609, 65), 
    'size':(52, 22), 
    'label':'Save', 
    },

{'type':'ComboBox', 
    'name':'SaveParVar', 
    'position':(524, 32), 
    'size':(198, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'saveParameters', 
    'position':(407, 37), 
    'text':'Save Parameters =', 
    },

{'type':'StaticText', 
    'name':'dataParameters', 
    'position':(399, 104), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'text':'Data Parameters', 
    },

{'type':'StaticLine', 
    'name':'StaticLine11', 
    'position':(538, 282), 
    'size':(2, 122), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'putButtonsForShowRoisEtcCheckDetectors', 
    'position':(102, 229), 
    'text':'Put buttons for show rois etc, check detectors', 
    },

{'type':'StaticText', 
    'name':'energyRange', 
    'position':(401, 226), 
    'text':'Energy Range =', 
    },

{'type':'CheckBox', 
    'name':'CorrectData', 
    'position':(626, 139), 
    'checked':True, 
    'label':'Correct Data', 
    },

{'type':'Button', 
    'name':'DelBgr', 
    'position':(74, 306), 
    'size':(49, 20), 
    'label':'Delete', 
    },

{'type':'Button', 
    'name':'AddBgr', 
    'position':(24, 305), 
    'size':(46, 20), 
    'label':'Add', 
    },

{'type':'MultiColumnList', 
    'name':'BgrParams', 
    'position':(21, 329), 
    'size':(515, 71), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Exponent', 'TopWidth', 'BottWidth', 'Tangent', 'Compress'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'Button', 
    'name':'ClearParamsAll', 
    'position':(707, 375), 
    'size':(38, -1), 
    'label':'Clear', 
    },

{'type':'Button', 
    'name':'ClearParamsDet', 
    'position':(708, 346), 
    'size':(38, -1), 
    'label':'Clear', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(17, 590), 
    'size':(735, 6), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'CopyParams', 
    'position':(707, 317), 
    'size':(38, -1), 
    'label':'Copy', 
    },

{'type':'ComboBox', 
    'name':'McaTaus', 
    'position':(479, 183), 
    'size':(232, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'BadMcas', 
    'position':(478, 158), 
    'size':(232, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'NumMcas', 
    'position':(404, 138), 
    'text':'NumMcas = 0', 
    },

{'type':'TextArea', 
    'name':'Messages', 
    'position':(15, 675), 
    'size':(734, 35), 
    'editable':False, 
    'text':'Messages', 
    },

{'type':'Slider', 
    'name':'PkFWHMSlider', 
    'position':(428, 460), 
    'size':(75, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':50, 
    },

{'type':'Slider', 
    'name':'pkAmpSlider', 
    'position':(329, 460), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':50, 
    },

{'type':'Slider', 
    'name':'pkEnSlider', 
    'position':(239, 460), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':50, 
    'min':-50, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'StaticLine', 
    'name':'StaticLine10', 
    'position':(15, 714), 
    'size':(740, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'XrfLineL', 
    'position':(110, 458), 
    'size':(30, -1), 
    'checked':True, 
    'label':'L', 
    },

{'type':'CheckBox', 
    'name':'XrfLineK', 
    'position':(78, 458), 
    'checked':True, 
    'label':'K', 
    },

{'type':'StaticText', 
    'name':'IgnoreLbl', 
    'position':(702, 418), 
    'size':(-1, 19), 
    'text':'Ignore', 
    },

{'type':'StaticText', 
    'name':'PkLblLbl', 
    'position':(177, 417), 
    'text':'Label', 
    },

{'type':'TextField', 
    'name':'PkLbl', 
    'position':(152, 437), 
    'size':(76, -1), 
    },

{'type':'Button', 
    'name':'UpdateTdl', 
    'position':(18, 30), 
    'size':(88, 25), 
    'label':'Update Variables', 
    },

{'type':'StaticLine', 
    'name':'StaticLine9', 
    'position':(10, 668), 
    'size':(745, 6), 
    'layout':'horizontal', 
    },

{'type':'ComboBox', 
    'name':'FitChiExp', 
    'position':(334, 617), 
    'size':(60, -1), 
    'items':[u'0.0', u'0.5', u'1.0'], 
    'stringSelection':'0.0', 
    'text':'0.0', 
    },

{'type':'ComboBox', 
    'name':'FitEnFlag', 
    'position':(254, 617), 
    'size':(60, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'1', 
    'text':'1', 
    },

{'type':'ComboBox', 
    'name':'FitFWHMFlag', 
    'position':(174, 616), 
    'size':(60, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'1', 
    'text':'1', 
    },

{'type':'StaticText', 
    'name':'FitChiExpLbl', 
    'position':(329, 597), 
    'text':'Chi Exponent', 
    },

{'type':'StaticText', 
    'name':'FitEnergyFlagLbl', 
    'position':(254, 597), 
    'text':'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FitFWHMFlagLbl', 
    'position':(174, 597), 
    'text':'FWHM Flag', 
    },

{'type':'Button', 
    'name':'XrfLineDel', 
    'position':(22, 445), 
    'size':(45, 22), 
    'label':'Delete', 
    },

{'type':'TextField', 
    'name':'PkAmpFactor', 
    'position':(632, 437), 
    'size':(64, -1), 
    },

{'type':'TextField', 
    'name':'PkFwhmFlag', 
    'position':(577, 437), 
    'size':(47, -1), 
    },

{'type':'TextField', 
    'name':'PkEnFlag', 
    'position':(517, 437), 
    'size':(49, -1), 
    },

{'type':'TextField', 
    'name':'PkFWHM', 
    'position':(422, 437), 
    'size':(82, -1), 
    },

{'type':'TextField', 
    'name':'PkAmp', 
    'position':(327, 437), 
    'size':(85, -1), 
    },

{'type':'TextField', 
    'name':'PkEn', 
    'position':(237, 437), 
    'size':(80, -1), 
    },

{'type':'CheckBox', 
    'name':'PkIgnore', 
    'position':(713, 437), 
    'size':(14, 19), 
    'label':'CheckBox', 
    },

{'type':'StaticText', 
    'name':'AmpFactorLbl', 
    'position':(638, 406), 
    'size':(56, 29), 
    'text':'Amplitude Factor', 
    },

{'type':'StaticText', 
    'name':'FwhmFlagLbl', 
    'position':(578, 406), 
    'size':(44, 26), 
    'text':'FWHM Flag', 
    },

{'type':'StaticText', 
    'name':'EFlagLbl', 
    'position':(524, 406), 
    'size':(43, 28), 
    'text':'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FwhmLbl', 
    'position':(447, 417), 
    'text':'FWHM', 
    },

{'type':'StaticText', 
    'name':'AmpLbl', 
    'position':(342, 417), 
    'text':'Amplitude', 
    },

{'type':'StaticText', 
    'name':'EnergyLbl', 
    'position':(257, 417), 
    'text':'Energy', 
    },

{'type':'CheckBox', 
    'name':'XrfLineShow', 
    'position':(236, 180), 
    'size':(90, -1), 
    'label':'Show XRF Lines', 
    },

{'type':'Button', 
    'name':'XrfLineAdd', 
    'position':(22, 420), 
    'size':(45, 22), 
    'label':'Add', 
    },

{'type':'StaticLine', 
    'name':'StaticLine8', 
    'position':(16, 404), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'BgrDefault', 
    'position':(490, 304), 
    'size':(45, 22), 
    'label':'Default', 
    },

{'type':'StaticLine', 
    'name':'StaticLine7', 
    'position':(20, 282), 
    'size':(729, -1), 
    'layout':'horizontal', 
    },

{'type':'TextField', 
    'name':'BgrCompress', 
    'position':(429, 305), 
    'size':(55, 19), 
    'text':'4', 
    },

{'type':'TextField', 
    'name':'BgrTangent', 
    'position':(373, 304), 
    'size':(45, 19), 
    'text':'0', 
    },

{'type':'TextField', 
    'name':'BgrBtmWdth', 
    'position':(289, 305), 
    'size':(75, 19), 
    'text':'4.0', 
    },

{'type':'TextField', 
    'name':'BgrTopWdth', 
    'position':(212, 305), 
    'size':(70, 19), 
    'text':'0.0', 
    },

{'type':'TextField', 
    'name':'BgrExp', 
    'position':(130, 305), 
    'size':(75, 19), 
    'text':'2', 
    },

{'type':'StaticText', 
    'name':'FitParamDetLbl', 
    'position':(553, 263), 
    'text':'Detector=', 
    },

{'type':'Choice', 
    'name':'DetSelect', 
    'position':(621, 258), 
    'size':(77, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    },

{'type':'StaticText', 
    'name':'FittingParamsLbl', 
    'position':(22, 259), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 12}, 
    'text':'Fit Parameters', 
    },

{'type':'StaticText', 
    'name':'BgrCompressLbl', 
    'position':(434, 289), 
    'text':'Compress', 
    },

{'type':'StaticText', 
    'name':'BgrTangentLbl', 
    'position':(376, 289), 
    'text':'Tangent', 
    },

{'type':'StaticText', 
    'name':'BgrBtmWidthLbl', 
    'position':(295, 288), 
    'text':'Bottom Width', 
    },

{'type':'StaticText', 
    'name':'BgrTopWidthLbl', 
    'position':(221, 288), 
    'text':'Top Width', 
    },

{'type':'StaticText', 
    'name':'BgrExpLbl', 
    'position':(143, 288), 
    'text':'Exponent', 
    },

{'type':'StaticText', 
    'name':'SetIncIncLabel', 
    'position':(301, 68), 
    'text':'Step', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(10, 7), 
    'size':(745, 7), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(750, 10), 
    'size':(5, 708), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(390, 96), 
    'size':(5, 154), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(10, 12), 
    'size':(6, 708), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'ComponentsCheck', 
    'position':(180, 203), 
    'size':(76, -1), 
    'label':'Components', 
    },

{'type':'StaticText', 
    'name':'TauListLbl', 
    'position':(405, 185), 
    'text':'McaTaus = ', 
    'toolTip':'Provide Tdl variable holding Tau values', 
    },

{'type':'CheckBox', 
    'name':'Align', 
    'position':(573, 139), 
    'checked':True, 
    'label':'Align', 
    },

{'type':'CheckBox', 
    'name':'Total', 
    'position':(515, 139), 
    'checked':True, 
    'label':'Total', 
    },

{'type':'StaticText', 
    'name':'McaListLbl', 
    'position':(403, 161), 
    'text':'Bad Mcas = ', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'CheckBox', 
    'name':'AutoIncCheck', 
    'position':(26, 65), 
    'size':(40, 20), 
    'label':'Scan', 
    },

{'type':'StaticText', 
    'name':'AutoIncStopLabel', 
    'position':(161, 68), 
    'text':'Stop', 
    },

{'type':'StaticText', 
    'name':'AutoIncStartLabel', 
    'position':(74, 68), 
    'text':'Start', 
    },

{'type':'TextField', 
    'name':'AutoIncStop', 
    'position':(191, 64), 
    'size':(43, -1), 
    'text':'0', 
    },

{'type':'TextField', 
    'name':'AutoIncStart', 
    'position':(109, 64), 
    'size':(40, -1), 
    'text':'0', 
    },

{'type':'StaticText', 
    'name':'ExtractLbl', 
    'position':(544, 613), 
    'text':'Extract', 
    },

{'type':'CheckBox', 
    'name':'YerrCheck', 
    'position':(182, 181), 
    'size':(49, -1), 
    'label':'Yerr', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(10, 250), 
    'size':(741, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'UsePrevFit', 
    'position':(299, 652), 
    'label':'Use Prev Fit', 
    },

{'type':'ComboBox', 
    'name':'InitScanIdx', 
    'position':(224, 646), 
    'size':(60, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'StaticText', 
    'name':'InitScanIdxLbl', 
    'position':(120, 651), 
    'text':'Index for scan init', 
    },

{'type':'Button', 
    'name':'UpdateXRF', 
    'position':(657, 287), 
    'size':(74, -1), 
    'label':'Update', 
    },

{'type':'Button', 
    'name':'FitScan', 
    'position':(29, 638), 
    'size':(57, -1), 
    'label':'Fit Scan', 
    },

{'type':'Button', 
    'name':'Fit', 
    'position':(99, 612), 
    'size':(57, -1), 
    'label':'Fit', 
    },

{'type':'MultiColumnList', 
    'name':'PkParams', 
    'position':(19, 475), 
    'size':(727, 113), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Label', 'Energy', 'Amp', 'FWHM', 'E-Flag', 'FWHM-Flag', 'Amp-Factor', 'Ignore', 'Area'], 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 7}, 
    'items':[], 
    'maxColumns':20, 
    'rules':False, 
    },

{'type':'Choice', 
    'name':'XrfLine', 
    'position':(73, 435), 
    'size':(74, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'BgrCheck', 
    'position':(31, 287), 
    'checked':True, 
    'label':'FitBackground', 
    },

{'type':'Button', 
    'name':'Calc', 
    'position':(29, 612), 
    'size':(57, -1), 
    'label':'Calc', 
    },

{'type':'StaticText', 
    'name':'XrfLineLbl', 
    'position':(82, 417), 
    'text':'XRF Line =', 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(30, 200), 
    'size':(55, -1), 
    'label':'Hold', 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(114, 202), 
    'size':(38, -1), 
    'label':'Ylog', 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(114, 180), 
    'size':(64, -1), 
    'label':'Xlog', 
    },

{'type':'Button', 
    'name':'EnRange', 
    'position':(682, 220), 
    'size':(42, -1), 
    'label':'Select', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(585, 222), 
    'size':(85, -1), 
    'text':'20.0', 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(593, 207), 
    'text':'Emax (keV)=', 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(490, 222), 
    'size':(85, -1), 
    'text':'2.0', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(505, 207), 
    'text':'Emin (keV)=', 
    },

{'type':'ComboBox', 
    'name':'FitFmt', 
    'position':(154, 154), 
    'size':(177, -1), 
    'items':[u'Fit', u'Fit+Bgr', u'Fit and Bgr'], 
    'stringSelection':'Fit', 
    'text':'Fit', 
    },

{'type':'ComboBox', 
    'name':'DataFmt', 
    'position':(155, 130), 
    'size':(176, -1), 
    'items':[u'Data', u'Data-Bgr', u'Raw Mcas: All', u'Raw Mcas Included'], 
    'text':'Data', 
    },

{'type':'Spinner', 
    'name':'NodeInc', 
    'position':(324, 64), 
    'size':(62, -1), 
    'max':10000000, 
    'min':-1000000, 
    'value':0, 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(31, 180), 
    'size':(77, 12), 
    'checked':True, 
    'label':'Auto Update', 
    },

{'type':'CheckBox', 
    'name':'FitPlotCheck', 
    'position':(86, 157), 
    'size':(39, -1), 
    'label':'Fit', 
    },

{'type':'CheckBox', 
    'name':'DataPlotCheck', 
    'position':(85, 134), 
    'checked':True, 
    'label':'Data', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(23, 131), 
    'size':(41, 30), 
    'label':'Plot', 
    },

{'type':'StaticText', 
    'name':'AutoIncIncLabel', 
    'position':(242, 68), 
    'text':'Inc', 
    },

{'type':'TextField', 
    'name':'AutoIncInc', 
    'position':(262, 64), 
    'size':(34, -1), 
    'text':'1', 
    },

{'type':'ComboBox', 
    'name':'NodePfx', 
    'position':(218, 35), 
    'size':(170, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Grp', 
    'position':(109, 34), 
    'size':(103, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'nodeLabel', 
    'position':(278, 19), 
    'text':'XRF node', 
    },

{'type':'StaticText', 
    'name':'grpLabel', 
    'position':(136, 18), 
    'text':'XRF group', 
    },

] # end components
} # end background
] # end backgrounds
} }
