{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'XRF',
          'size':(766, 786),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'Read XRF',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpParams',
                   'label':u'Parameters',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'UpdateShell', 
    'position':(15, 47), 
    'size':(83, 40), 
    'label':'Shell Update', 
    },

{'type':'ComboBox', 
    'name':'Grp', 
    'position':(180, 40), 
    'size':(124, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Node', 
    'position':(180, 68), 
    'size':(124, -1), 
    'items':[], 
    },

{'type':'Choice', 
    'name':'ScanIdxSelect', 
    'position':(395, 66), 
    'size':(66, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    },

{'type':'Button', 
    'name':'RestoreSavePar', 
    'position':(502, 67), 
    'size':(53, 22), 
    'label':'Restore', 
    },

{'type':'Button', 
    'name':'SaveSavePar', 
    'position':(502, 41), 
    'size':(52, 22), 
    'label':'Save', 
    },

{'type':'ComboBox', 
    'name':'SaveParVar', 
    'position':(581, 59), 
    'size':(139, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(25, 141), 
    'size':(47, 41), 
    'label':'Plot', 
    },

{'type':'ComboBox', 
    'name':'DataFmt', 
    'position':(162, 136), 
    'size':(129, -1), 
    'items':[u'Data', u'Data-Bgr'], 
    'stringSelection':'Data', 
    'text':'Data', 
    },

{'type':'ComboBox', 
    'name':'FitFmt', 
    'position':(161, 163), 
    'size':(128, -1), 
    'items':[u'Fit', u'Bgr', u'Fit-Bgr', u'Fit and Bgr'], 
    'stringSelection':'Fit', 
    'text':'Fit', 
    },

{'type':'ComboBox', 
    'name':'ExtractResultsVar', 
    'position':(605, 133), 
    'items':[], 
    'text':'results', 
    },

{'type':'Choice', 
    'name':'ExtractLineSelect', 
    'position':(605, 162), 
    'items':[], 
    },

{'type':'Button', 
    'name':'ExtractResults', 
    'position':(484, 156), 
    'size':(47, 25), 
    'label':'Extract', 
    },

{'type':'Button', 
    'name':'ClearParamsAll', 
    'position':(158, 200), 
    'size':(62, 20), 
    'label':'Clear', 
    },

{'type':'Button', 
    'name':'UpdateXRF', 
    'position':(228, 200), 
    'size':(59, 20), 
    'label':'Update', 
    },

{'type':'Button', 
    'name':'BgrDefault', 
    'position':(97, 233), 
    'size':(56, 29), 
    'label':'Default', 
    },

{'type':'TextField', 
    'name':'BgrBtmWdth', 
    'position':(176, 240), 
    'size':(47, 23), 
    'text':'4.0', 
    },

{'type':'TextField', 
    'name':'BgrTopWdth', 
    'position':(260, 241), 
    'size':(46, -1), 
    'text':'0.0', 
    },

{'type':'ComboBox', 
    'name':'BgrExp', 
    'position':(336, 241), 
    'size':(57, -1), 
    'items':[u'0', u'1', u'2', u'3', u'4', u'5'], 
    'stringSelection':'2', 
    'text':'2', 
    },

{'type':'Choice', 
    'name':'BgrTangent', 
    'position':(418, 241), 
    'size':(50, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'0', 
    },

{'type':'TextField', 
    'name':'BgrCompress', 
    'position':(498, 240), 
    'size':(42, 23), 
    'text':'4', 
    },

{'type':'Choice', 
    'name':'BgrBtmWdthFlag', 
    'position':(581, 241), 
    'size':(51, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'1', 
    },

{'type':'Choice', 
    'name':'BgrTopWdthFlag', 
    'position':(671, 241), 
    'size':(55, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'1', 
    },

{'type':'Choice', 
    'name':'XrfLine', 
    'position':(175, 274), 
    'size':(87, -1), 
    'items':[], 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(410, 274), 
    'size':(57, -1), 
    'text':'0', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(532, 274), 
    'size':(57, -1), 
    'text':'0', 
    },

{'type':'Button', 
    'name':'LineAdd', 
    'position':(22, 307), 
    'size':(47, 25), 
    'label':'Add', 
    },

{'type':'Button', 
    'name':'LineDel', 
    'position':(22, 335), 
    'size':(47, 26), 
    'label':'Delete', 
    },

{'type':'TextField', 
    'name':'PkLbl', 
    'position':(87, 337), 
    'size':(82, 23), 
    },

{'type':'TextField', 
    'name':'PkEn', 
    'position':(176, 337), 
    'size':(83, 22), 
    },

{'type':'TextField', 
    'name':'PkAmp', 
    'position':(270, 338), 
    'size':(89, -1), 
    },

{'type':'TextField', 
    'name':'PkFWHM', 
    'position':(365, 338), 
    'size':(92, -1), 
    },

{'type':'Choice', 
    'name':'PkEnFlag', 
    'position':(469, 338), 
    'size':(54, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'1', 
    },

{'type':'Choice', 
    'name':'PkFwhmFlag', 
    'position':(534, 338), 
    'size':(51, -1), 
    'items':[u'0', u'1', u'2'], 
    'stringSelection':'1', 
    },

{'type':'TextField', 
    'name':'PkAmpFactor', 
    'position':(601, 338), 
    'size':(64, -1), 
    'text':"u'0'", 
    },

{'type':'Button', 
    'name':'Calc', 
    'position':(20, 614), 
    'size':(49, 24), 
    'label':'Calc', 
    },

{'type':'Button', 
    'name':'Fit', 
    'position':(80, 615), 
    'size':(50, 24), 
    'label':'Fit', 
    },

{'type':'TextField', 
    'name':'FitEnOffset', 
    'position':(143, 651), 
    'size':(57, -1), 
    'text':'0.0', 
    },

{'type':'TextField', 
    'name':'FitEnSlope', 
    'position':(211, 651), 
    'size':(51, -1), 
    'text':'1.', 
    },

{'type':'ComboBox', 
    'name':'FitEnFlag', 
    'position':(273, 650), 
    'size':(52, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'TextField', 
    'name':'FitFwhmOffset', 
    'position':(340, 651), 
    'size':(52, -1), 
    'text':'0.15', 
    },

{'type':'TextField', 
    'name':'FitFwhmSlope', 
    'position':(403, 650), 
    'size':(45, -1), 
    'text':'0.', 
    },

{'type':'ComboBox', 
    'name':'FitFwhmFlag', 
    'position':(462, 650), 
    'size':(44, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'ComboBox', 
    'name':'FitChiExp', 
    'position':(517, 649), 
    'size':(60, -1), 
    'items':[u'0.0', u'0.5', u'1.0'], 
    'stringSelection':'0.0', 
    'text':'0.0', 
    },

{'type':'Button', 
    'name':'FitScan', 
    'position':(592, 615), 
    'size':(54, 30), 
    'label':'Fit Scan', 
    },

{'type':'Choice', 
    'name':'ScanInitIdxSelect', 
    'position':(662, 651), 
    'size':(71, -1), 
    'items':[u'-1'], 
    'stringSelection':'-1', 
    },

{'type':'MultiColumnList', 
    'name':'PkParams', 
    'position':(16, 364), 
    'size':(731, 237), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Label', 'Energy', 'Amp', 'FWHM', 'E-Flag', 'FWHM-Flag', 'Amp-Factor', 'Ignore', 'Area'], 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 7}, 
    'items':[], 
    'maxColumns':20, 
    'rules':False, 
    },

{'type':'CheckBox', 
    'name':'ShowPeakBgr', 
    'position':(401, 168), 
    'size':(69, -1), 
    'label':'Peak Bgr', 
    },

{'type':'CheckBox', 
    'name':'PeakGuess', 
    'position':(23, 647), 
    'label':'Guess', 
    },

{'type':'CheckBox', 
    'name':'UsePrevFit', 
    'position':(651, 621), 
    'size':(90, -1), 
    'label':'Use Previous', 
    },

{'type':'CheckBox', 
    'name':'SetParFromSave', 
    'position':(317, 43), 
    'size':(152, -1), 
    'label':'Set Params From Save', 
    },

{'type':'CheckBox', 
    'name':'XrfLineL', 
    'position':(318, 278), 
    'size':(30, -1), 
    'checked':True, 
    'label':'L', 
    },

{'type':'CheckBox', 
    'name':'XrfLineK', 
    'position':(283, 278), 
    'checked':True, 
    'label':'K', 
    },

{'type':'CheckBox', 
    'name':'PkIgnore', 
    'position':(682, 339), 
    'size':(-1, 19), 
    'label':'Ignore', 
    },

{'type':'CheckBox', 
    'name':'ShowPeak', 
    'position':(401, 141), 
    'size':(45, -1), 
    'label':'Peaks', 
    },

{'type':'CheckBox', 
    'name':'YerrCheck', 
    'position':(352, 140), 
    'size':(45, -1), 
    'label':'Yerr', 
    },

{'type':'CheckBox', 
    'name':'BgrCheck', 
    'position':(23, 668), 
    'size':(105, -1), 
    'label':'Fit Background', 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(351, 168), 
    'size':(45, -1), 
    'label':'Hold', 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(301, 167), 
    'size':(42, -1), 
    'checked':True, 
    'label':'Ylog', 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(300, 140), 
    'size':(44, -1), 
    'label':'Xlog', 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(177, 108), 
    'size':(99, 15), 
    'checked':True, 
    'label':'Auto Update', 
    },

{'type':'CheckBox', 
    'name':'FitPlotCheck', 
    'position':(90, 170), 
    'size':(39, -1), 
    'checked':True, 
    'label':'Fit', 
    },

{'type':'CheckBox', 
    'name':'DataPlotCheck', 
    'position':(89, 143), 
    'checked':True, 
    'label':'Data', 
    },

{'type':'StaticText', 
    'name':'ExtractLineSelectLbl', 
    'position':(569, 166), 
    'text':'Line', 
    },

{'type':'StaticText', 
    'name':'ExtractResultsLbl', 
    'position':(486, 104), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 11}, 
    'text':'Extract Results', 
    },

{'type':'StaticText', 
    'name':'SaveParLbl', 
    'position':(487, 12), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 11}, 
    'text':'Save Parameters', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(584, 608), 
    'size':(4, 76), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'FitFwhmSlopeLbl', 
    'position':(403, 613), 
    'size':(36, 31), 
    'text':'FWHM Slope', 
    },

{'type':'StaticText', 
    'name':'FitFwhmOffsetLbl', 
    'position':(345, 615), 
    'size':(40, 33), 
    'text':'FWHM Offset', 
    },

{'type':'StaticText', 
    'name':'FitEnSlopeLbl', 
    'position':(218, 614), 
    'size':(42, 34), 
    'text':'Energy Slope', 
    },

{'type':'StaticText', 
    'name':'FitEnOffsetLbl', 
    'position':(154, 615), 
    'size':(39, 31), 
    'text':'Energy Offset', 
    },

{'type':'StaticText', 
    'name':'BgrBtmWdthFlagLbl', 
    'position':(580, 207), 
    'size':(67, 31), 
    'text':'Bottom Width Fixed', 
    },

{'type':'StaticText', 
    'name':'BgrTopWdthFlagLbl', 
    'position':(672, 208), 
    'size':(59, 30), 
    'text':'Top Width Fixed', 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(494, 278), 
    'text':'Emax', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(371, 278), 
    'text':'Emin', 
    },

{'type':'StaticText', 
    'name':'FitScanIdxLbl', 
    'position':(593, 655), 
    'text':'Initialize =', 
    },

{'type':'StaticLine', 
    'name':'StaticLine81', 
    'position':(16, 300), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'xrfLinesLbl', 
    'position':(21, 275), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'text':'Xrf Lines', 
    },

{'type':'StaticText', 
    'name':'bgrParamsLbl', 
    'position':(21, 240), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'text':'Background', 
    },

{'type':'StaticLine', 
    'name':'StaticLine42', 
    'position':(473, 10), 
    'size':(3, 183), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine15', 
    'position':(16, 127), 
    'size':(732, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'plotParametersLbl', 
    'position':(21, 104), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 11}, 
    'text':'Plot Parameters', 
    },

{'type':'StaticLine', 
    'name':'StaticLine13', 
    'position':(13, 98), 
    'size':(738, 6), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine12', 
    'position':(15, 34), 
    'size':(734, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'saveParameters', 
    'position':(597, 42), 
    'text':'Save Parameters =', 
    },

{'type':'StaticText', 
    'name':'xrfDatalbl', 
    'position':(22, 11), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 11}, 
    'text':'Xrf Data', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(11, 604), 
    'size':(741, 6), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine10', 
    'position':(10, 685), 
    'size':(744, 6), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'PkLblLbl', 
    'position':(111, 317), 
    'text':'Label', 
    },

{'type':'StaticText', 
    'name':'FitChiExpLbl', 
    'position':(521, 610), 
    'size':(56, 33), 
    'text':'Chi Exponent', 
    },

{'type':'StaticText', 
    'name':'FitEnergyFlagLbl', 
    'position':(276, 613), 
    'size':(50, 31), 
    'text':'Energy Fixed', 
    },

{'type':'StaticText', 
    'name':'FitFWHMFlagLbl', 
    'position':(464, 613), 
    'size':(40, 33), 
    'text':'FWHM Fixed', 
    },

{'type':'StaticText', 
    'name':'AmpFactorLbl', 
    'position':(606, 301), 
    'size':(56, 29), 
    'text':'Amplitude Factor', 
    },

{'type':'StaticText', 
    'name':'FwhmFlagLbl', 
    'position':(539, 302), 
    'size':(43, 29), 
    'text':'FWHM Fixed', 
    },

{'type':'StaticText', 
    'name':'EFlagLbl', 
    'position':(472, 302), 
    'size':(51, 31), 
    'text':'Energy Fixed', 
    },

{'type':'StaticText', 
    'name':'FwhmLbl', 
    'position':(392, 316), 
    'text':'FWHM', 
    },

{'type':'StaticText', 
    'name':'AmpLbl', 
    'position':(285, 315), 
    'text':'Amplitude', 
    },

{'type':'StaticText', 
    'name':'EnergyLbl', 
    'position':(200, 314), 
    'text':'Energy', 
    },

{'type':'StaticLine', 
    'name':'StaticLine8', 
    'position':(19, 267), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine7', 
    'position':(11, 221), 
    'size':(284, 3), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'ScanIdxLbl', 
    'position':(319, 71), 
    'text':'Scan Index=', 
    },

{'type':'StaticText', 
    'name':'FittingParamsLbl', 
    'position':(17, 198), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 11}, 
    'text':'Fit Parameters', 
    },

{'type':'StaticText', 
    'name':'BgrCompressLbl', 
    'position':(490, 225), 
    'text':'Compress', 
    },

{'type':'StaticText', 
    'name':'BgrTangentLbl', 
    'position':(419, 225), 
    'text':'Tangent', 
    },

{'type':'StaticText', 
    'name':'BgrBtmWidthLbl', 
    'position':(166, 225), 
    'text':'Bottom Width', 
    },

{'type':'StaticText', 
    'name':'BgrTopWidthLbl', 
    'position':(254, 225), 
    'text':'Top Width', 
    },

{'type':'StaticText', 
    'name':'BgrExpLbl', 
    'position':(338, 225), 
    'text':'Exponent', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(10, 4), 
    'size':(743, 7), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(749, 4), 
    'size':(5, 685), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(5, 4), 
    'size':(6, 687), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'ExtractLbl', 
    'position':(539, 136), 
    'text':'Extract To', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(13, 192), 
    'size':(741, 6), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'XrfLineLbl', 
    'position':(102, 278), 
    'text':'XRF Line =', 
    },

{'type':'StaticText', 
    'name':'nodeLabel', 
    'position':(114, 72), 
    'text':'XRF name', 
    },

{'type':'StaticText', 
    'name':'grpLabel', 
    'position':(114, 46), 
    'text':'XRF group', 
    },

] # end components
} # end background
] # end backgrounds
} }
