{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'XRF',
          'size':(779, 794),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'CheckBox', 
    'name':'CorrectData', 
    'position':(577, 46), 
    'checked':True, 
    'label':u'Correct Data', 
    },

{'type':'Button', 
    'name':'DelBgr', 
    'position':(84, 303), 
    'size':(49, 20), 
    'label':u'Delete', 
    },

{'type':'Button', 
    'name':'AddBgr', 
    'position':(34, 302), 
    'size':(46, 20), 
    'label':u'Add', 
    },

{'type':'MultiColumnList', 
    'name':'BgrParams', 
    'position':(31, 325), 
    'size':(515, 71), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Exponent', 'TopWidth', 'BottWidth', 'Tangent', 'Compress'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'Button', 
    'name':'UpdateParams', 
    'position':(611, 338), 
    'size':(82, -1), 
    'label':u'Update', 
    },

{'type':'Button', 
    'name':'ClearAll', 
    'position':(610, 310), 
    'size':(77, -1), 
    'label':u'ClearAll', 
    },

{'type':'Button', 
    'name':'ClearDet', 
    'position':(602, 282), 
    'size':(94, -1), 
    'label':u'ClearDetector', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(26, 587), 
    'size':(730, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'CopyAllPkParams', 
    'position':(314, 249), 
    'label':u'CopyToAllDetectors', 
    },

{'type':'ComboBox', 
    'name':'McaTaus', 
    'position':(505, 96), 
    'size':(232, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'BadMcas', 
    'position':(506, 67), 
    'size':(232, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'NumMcas', 
    'position':(440, 20), 
    'text':u'NumMcas = 0', 
    },

{'type':'TextArea', 
    'name':'Messages', 
    'position':(24, 675), 
    'size':(734, 35), 
    'editable':False, 
    'text':u'Messages', 
    },

{'type':'Slider', 
    'name':'PkFWHMSlider', 
    'position':(438, 460), 
    'size':(75, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':11, 
    },

{'type':'Slider', 
    'name':'pkAmpSlider', 
    'position':(340, 460), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'Slider', 
    'name':'pkEnSlider', 
    'position':(249, 460), 
    'size':(77, 14), 
    'labels':False, 
    'layout':'horizontal', 
    'max':50, 
    'min':-50, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':0, 
    },

{'type':'StaticLine', 
    'name':'StaticLine10', 
    'position':(19, 714), 
    'size':(745, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'XrfLineL', 
    'position':(122, 454), 
    'size':(30, -1), 
    'label':u'L', 
    },

{'type':'CheckBox', 
    'name':'XrfLineK', 
    'position':(88, 454), 
    'label':u'K', 
    },

{'type':'StaticText', 
    'name':'IgnoreLbl', 
    'position':(712, 412), 
    'size':(-1, 19), 
    'text':u'Ignore', 
    },

{'type':'StaticText', 
    'name':'PkLblLbl', 
    'position':(187, 417), 
    'text':u'Label', 
    },

{'type':'TextField', 
    'name':'PkLbl', 
    'position':(162, 437), 
    'size':(76, -1), 
    },

{'type':'Button', 
    'name':'UpdateMenus', 
    'position':(41, 36), 
    'size':(48, 28), 
    'label':u'Update', 
    },

{'type':'StaticLine', 
    'name':'StaticLine9', 
    'position':(20, 668), 
    'size':(744, 6), 
    'layout':'horizontal', 
    },

{'type':'ComboBox', 
    'name':'FitChiExp', 
    'position':(344, 613), 
    'size':(60, -1), 
    'items':[u'0.0', u'0.5', u'1.0'], 
    'stringSelection':u'0.0', 
    'text':u'0.0', 
    },

{'type':'ComboBox', 
    'name':'FitEnFlag', 
    'position':(264, 613), 
    'size':(60, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':u'1', 
    'text':u'1', 
    },

{'type':'ComboBox', 
    'name':'FitFWHMFlag', 
    'position':(184, 612), 
    'size':(60, -1), 
    'items':[u'0', u'1'], 
    'stringSelection':u'1', 
    'text':u'1', 
    },

{'type':'StaticText', 
    'name':'FitChiExpLbl', 
    'position':(339, 593), 
    'text':u'Chi Exponent', 
    },

{'type':'StaticText', 
    'name':'FitEnergyFlagLbl', 
    'position':(264, 593), 
    'text':u'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FitFWHMFlagLbl', 
    'position':(184, 593), 
    'text':u'FWHM Flag', 
    },

{'type':'Button', 
    'name':'XrfLineDel', 
    'position':(32, 442), 
    'size':(45, 25), 
    'label':u'Delete', 
    },

{'type':'TextField', 
    'name':'PkAmpFactor', 
    'position':(642, 437), 
    'size':(64, -1), 
    },

{'type':'TextField', 
    'name':'PkFwhmFlag', 
    'position':(587, 437), 
    'size':(47, -1), 
    },

{'type':'TextField', 
    'name':'PkEnFlag', 
    'position':(527, 437), 
    'size':(49, -1), 
    },

{'type':'TextField', 
    'name':'PkFWHM', 
    'position':(432, 437), 
    'size':(82, -1), 
    },

{'type':'TextField', 
    'name':'PkAmp', 
    'position':(337, 437), 
    'size':(85, -1), 
    },

{'type':'TextField', 
    'name':'PkEn', 
    'position':(247, 437), 
    'size':(80, -1), 
    },

{'type':'CheckBox', 
    'name':'PkIgnore', 
    'position':(717, 437), 
    'size':(14, 19), 
    'label':u'CheckBox', 
    },

{'type':'StaticText', 
    'name':'AmpFactorLbl', 
    'position':(647, 402), 
    'size':(56, 29), 
    'text':u'Amplitude Factor', 
    },

{'type':'StaticText', 
    'name':'FwhmFlagLbl', 
    'position':(587, 402), 
    'size':(43, 32), 
    'text':u'FWHM Flag', 
    },

{'type':'StaticText', 
    'name':'EFlagLbl', 
    'position':(532, 402), 
    'size':(42, 32), 
    'text':u'Energy Flag', 
    },

{'type':'StaticText', 
    'name':'FwhmLbl', 
    'position':(457, 417), 
    'text':u'FWHM', 
    },

{'type':'StaticText', 
    'name':'AmpLbl', 
    'position':(352, 417), 
    'text':u'Amplitude', 
    },

{'type':'StaticText', 
    'name':'EnergyLbl', 
    'position':(267, 417), 
    'text':u'Energy', 
    },

{'type':'CheckBox', 
    'name':'XrfLineShow', 
    'position':(321, 190), 
    'size':(90, -1), 
    'label':u'Show XRF Lines', 
    },

{'type':'Button', 
    'name':'XrfLineAdd', 
    'position':(32, 417), 
    'size':(45, 25), 
    'label':u'Add', 
    },

{'type':'StaticLine', 
    'name':'StaticLine8', 
    'position':(26, 398), 
    'size':(727, -1), 
    'layout':'horizontal', 
    },

{'type':'Button', 
    'name':'BgrDefault', 
    'position':(500, 299), 
    'size':(45, 22), 
    'label':u'Default', 
    },

{'type':'StaticLine', 
    'name':'StaticLine7', 
    'position':(30, 275), 
    'size':(716, -1), 
    'layout':'horizontal', 
    },

{'type':'TextField', 
    'name':'BgrCompress', 
    'position':(439, 300), 
    'size':(55, 19), 
    'text':u'4', 
    },

{'type':'TextField', 
    'name':'BgrTangent', 
    'position':(383, 299), 
    'size':(45, 19), 
    'text':u'0', 
    },

{'type':'TextField', 
    'name':'BgrBtmWdth', 
    'position':(299, 300), 
    'size':(75, 19), 
    'text':u'4.0', 
    },

{'type':'TextField', 
    'name':'BgrTopWdth', 
    'position':(222, 300), 
    'size':(70, 19), 
    'text':u'0.0', 
    },

{'type':'TextField', 
    'name':'BgrExp', 
    'position':(140, 300), 
    'size':(75, 19), 
    'text':u'2', 
    },

{'type':'StaticText', 
    'name':'FitParamDetLbl', 
    'position':(160, 253), 
    'text':u'Detector=', 
    },

{'type':'Choice', 
    'name':'DetSelect', 
    'position':(229, 250), 
    'size':(70, -1), 
    'items':[u'0'], 
    'stringSelection':u'0', 
    },

{'type':'StaticText', 
    'name':'FittingParamsLbl', 
    'position':(30, 250), 
    'font':{'faceName': u'MS Shell Dlg 2', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Fitting Parameters', 
    },

{'type':'StaticText', 
    'name':'BgrCompressLbl', 
    'position':(444, 284), 
    'text':u'Compress', 
    },

{'type':'StaticText', 
    'name':'BgrTangentLbl', 
    'position':(386, 284), 
    'text':u'Tangent', 
    },

{'type':'StaticText', 
    'name':'BgrBtmWidthLbl', 
    'position':(305, 283), 
    'text':u'Bottom Width', 
    },

{'type':'StaticText', 
    'name':'BgrTopWidthLbl', 
    'position':(231, 283), 
    'text':u'Top Width', 
    },

{'type':'StaticText', 
    'name':'BgrExpLbl', 
    'position':(153, 283), 
    'text':u'Exponent', 
    },

{'type':'StaticText', 
    'name':'SetIncIncLabel', 
    'position':(335, 70), 
    'text':u'Step', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(20, 10), 
    'size':(744, 7), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(760, 10), 
    'size':(5, 708), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(420, 10), 
    'size':(5, 232), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(19, 13), 
    'size':(5, 708), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'ComponentsCheck', 
    'position':(265, 213), 
    'size':(76, -1), 
    'label':u'Components', 
    },

{'type':'StaticText', 
    'name':'TauListLbl', 
    'position':(438, 99), 
    'text':u'McaTaus = ', 
    'toolTip':u'Provide Tdl variable holding Tau values', 
    },

{'type':'CheckBox', 
    'name':'Align', 
    'position':(510, 45), 
    'checked':True, 
    'label':u'Align', 
    },

{'type':'CheckBox', 
    'name':'Total', 
    'position':(445, 45), 
    'checked':True, 
    'label':u'Total', 
    },

{'type':'StaticText', 
    'name':'McaListLbl', 
    'position':(440, 70), 
    'text':u'Bad Mcas = ', 
    'toolTip':u'Provide Tdl variable hodling values', 
    },

{'type':'CheckBox', 
    'name':'AutoIncCheck', 
    'position':(45, 90), 
    'size':(50, 20), 
    'label':u'Scan', 
    },

{'type':'StaticText', 
    'name':'AutoIncStopLabel', 
    'position':(190, 70), 
    'text':u'Stop', 
    },

{'type':'StaticText', 
    'name':'AutoIncStartLabel', 
    'position':(125, 70), 
    'text':u'Start', 
    },

{'type':'TextField', 
    'name':'AutoIncStop', 
    'position':(180, 90), 
    'size':(56, -1), 
    'text':u'0', 
    },

{'type':'TextField', 
    'name':'AutoIncStart', 
    'position':(115, 90), 
    'size':(60, -1), 
    'text':u'0', 
    },

{'type':'StaticText', 
    'name':'ExtractLbl', 
    'position':(554, 613), 
    'text':u'Extract', 
    },

{'type':'CheckBox', 
    'name':'YerrCheck', 
    'position':(267, 191), 
    'size':(49, -1), 
    'label':u'Yerr', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(20, 240), 
    'size':(741, 6), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'UsePrevFit', 
    'position':(309, 648), 
    'label':u'Use Prev Fit', 
    },

{'type':'ComboBox', 
    'name':'InitScanIdx', 
    'position':(234, 643), 
    'size':(60, -1), 
    'items':[u'0'], 
    'stringSelection':u'0', 
    'text':u'0', 
    },

{'type':'StaticText', 
    'name':'InitScanIdxLbl', 
    'position':(119, 648), 
    'text':u'Index for scan init', 
    },

{'type':'Button', 
    'name':'UpdateData', 
    'position':(432, 143), 
    'size':(67, -1), 
    'label':u'Update Data', 
    },

{'type':'Button', 
    'name':'FitScan', 
    'position':(39, 638), 
    'size':(57, -1), 
    'label':u'Fit Scan', 
    },

{'type':'Button', 
    'name':'Fit', 
    'position':(109, 608), 
    'size':(57, -1), 
    'label':u'Fit', 
    },

{'type':'MultiColumnList', 
    'name':'PkParams', 
    'position':(27, 474), 
    'size':(727, 105), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Det', 'Label', 'Energy', 'Amp', 'FWHM', 'E-Flag', 'FWHM-Flag', 'Amp-Factor', 'Ignore', 'Area'], 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 7}, 
    'items':[], 
    'maxColumns':20, 
    'rules':False, 
    },

{'type':'Choice', 
    'name':'XrfLine', 
    'position':(83, 430), 
    'size':(74, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'BgrCheck', 
    'position':(41, 282), 
    'checked':True, 
    'label':u'FitBackground', 
    },

{'type':'Button', 
    'name':'Calc', 
    'position':(39, 608), 
    'size':(57, -1), 
    'label':u'Calc', 
    },

{'type':'StaticText', 
    'name':'XrfLineLbl', 
    'position':(88, 410), 
    'text':u'XRF Line =', 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(115, 215), 
    'size':(55, -1), 
    'label':u'Hold', 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(200, 215), 
    'size':(38, -1), 
    'label':u'Ylog', 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(199, 190), 
    'size':(64, -1), 
    'label':u'Xlog', 
    },

{'type':'Button', 
    'name':'EnRange', 
    'position':(705, 146), 
    'size':(42, -1), 
    'label':u'Select', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(608, 146), 
    'size':(85, -1), 
    'text':u'20.0', 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(606, 128), 
    'text':u'Emax (keV)=', 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(509, 146), 
    'size':(85, -1), 
    'text':u'2.0', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(515, 128), 
    'text':u'Emin (keV)=', 
    },

{'type':'ComboBox', 
    'name':'FitFmt', 
    'position':(115, 160), 
    'size':(202, -1), 
    'items':[u'Fit', u'Fit+Bgr', u'Fit and Bgr'], 
    },

{'type':'ComboBox', 
    'name':'DataFmt', 
    'position':(115, 125), 
    'size':(203, -1), 
    'items':[u'Data', u'Data-Bgr', u'Raw Mcas: All', u'Raw Mcas Included'], 
    'text':u'Data', 
    },

{'type':'Spinner', 
    'name':'NodeInc', 
    'position':(320, 90), 
    'size':(75, -1), 
    'max':10000000, 
    'min':-1000000, 
    'value':0, 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(115, 190), 
    'size':(77, 12), 
    'checked':True, 
    'label':u'Auto Update', 
    },

{'type':'CheckBox', 
    'name':'FitPlotCheck', 
    'position':(45, 160), 
    'size':(39, -1), 
    'label':u'Fit', 
    },

{'type':'CheckBox', 
    'name':'DataPlotCheck', 
    'position':(45, 130), 
    'checked':True, 
    'label':u'Data', 
    },

{'type':'Button', 
    'name':'Plot', 
    'position':(40, 192), 
    'size':(43, 35), 
    'label':u'Plot', 
    },

{'type':'StaticText', 
    'name':'AutoIncIncLabel', 
    'position':(245, 70), 
    'text':u'Inc', 
    },

{'type':'TextField', 
    'name':'AutoIncInc', 
    'position':(245, 90), 
    'size':(60, -1), 
    'text':u'1', 
    },

{'type':'ComboBox', 
    'name':'NodePfx', 
    'position':(220, 40), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'ComboBox', 
    'name':'Grp', 
    'position':(105, 40), 
    'size':(110, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'nodeLabel', 
    'position':(285, 20), 
    'text':u'XRF node', 
    },

{'type':'StaticText', 
    'name':'grpLabel', 
    'position':(130, 20), 
    'text':u'XRF group', 
    },

] # end components
} # end background
] # end backgrounds
} }
