#!python
"""
Startup pds
"""
##############################################################
import sys
args = sys.argv[1:]
if len(args) > 0:
    if args[0].lower() == 'pds':
        args.pop(0)

try:
    from tdl import pds
    pds.main(args)
except:
    import pds
    pds.main(args)
else:
    print "Error starting pds"
    return