#!python
"""
Startup tdl
"""
##############################################################
import sys
args = sys.argv[1:]
pds = True
if len(args) > 0:
    if args[0].lower() == 'pds':
        pds = True
        args.pop(0)

if pds:
    #from pds.lib.shell import main
    import pds
    pds.lib.main(args)
else:
    #from larch.shell import shell
    #shell(debug=True, scripts = args).cmdloop()
    pass
