#!/usr/bin/env python2.6

try:
    import lib as larch
except:
    import larch
    
import sys
from optparse import OptionParser

usage = "usage: %prog [options] file"
parser = OptionParser(usage=usage, prog="larch",
                      version="%s" % larch.__version__)
parser.add_option("-q", "--quiet", dest="quiet", action="store_true",
                  default=False, help="set quiet mode, default = False")
parser.add_option("-d", "--debug", dest="debug", action="store_true",
                  default=True, help="set debug mode, default = True")
(options, args) = parser.parse_args()

t = larch.shell(debug=options.debug)

if len(args)>0:
    for s in args:
        if s.endswith('.py'):    s = s[:-3]
        elif s.endswith('.lar'): s = s[:-4]
        t.default("import %s" % s)
else:
    t.cmdloop()

