{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxXRF_bgTemplate',
          'title':u'Spec Data',
          'size':(586, 786),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadXrf',
                   'label':u'ReadXrfFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveScript',
                   'label':'SaveScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileLoadScript',
                   'label':'LoadScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpDocumentation',
                   'label':u'Documentation',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'ScanPntLess', 
    'position':(418, 545), 
    'size':(30, 24), 
    'label':'<', 
    },

{'type':'Button', 
    'name':'ScanPntMore', 
    'position':(518, 545), 
    'size':(30, 24), 
    'label':'>', 
    },

{'type':'StaticBox', 
    'name':'StaticBox6', 
    'position':(465, 95), 
    'size':(96, 58), 
    },

{'type':'CheckBox', 
    'name':'ScalerGrid', 
    'position':(149, 559), 
    'label':'Grid', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(373, 29), 
    'text':'Lists from shell, and spec files', 
    },

{'type':'TextField', 
    'name':'ImageROI', 
    'position':(100, 474), 
    'size':(160, -1), 
    },

{'type':'Button', 
    'name':'BadPixelMapSel', 
    'position':(510, 475), 
    'size':(46, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'text11', 
    'position':(275, 478), 
    'text':'Bad Pixel Map', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'BadPixelMap', 
    'position':(361, 475), 
    'size':(140, -1), 
    },

{'type':'Button', 
    'name':'ImgArchivePathSel', 
    'position':(509, 443), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'text1', 
    'position':(17, 447), 
    'text':'Archive Path', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'ImageArchivePath', 
    'position':(101, 445), 
    'size':(398, -1), 
    },

{'type':'CheckBox', 
    'name':'ScalerDerivative', 
    'position':(215, 559), 
    'label':'Derivative', 
    },

{'type':'StaticText', 
    'name':'test12', 
    'position':(63, 477), 
    'text':'ROI', 
    },

{'type':'StaticText', 
    'name':'colormap', 
    'position':(455, 614), 
    'text':'colormap', 
    },

{'type':'Choice', 
    'name':'ColorMap', 
    'position':(433, 629), 
    'size':(105, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(6, 160), 
    'size':(558, 56), 
    'label':'Scan Variable', 
    },

{'type':'Button', 
    'name':'ImgPathSel', 
    'position':(509, 418), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'TextField', 
    'name':'ImagePath', 
    'position':(101, 418), 
    'size':(400, -1), 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(25, 420), 
    'text':'Image Path', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(263, 26), 
    'size':(99, 22), 
    'label':'Update', 
    },

{'type':'StaticText', 
    'name':'Lbl2', 
    'position':(20, 30), 
    'text':'ReaderName', 
    },

{'type':'ComboBox', 
    'name':'Reader', 
    'position':(102, 26), 
    'size':(132, -1), 
    'items':[u'reader'], 
    'stringSelection':'reader', 
    'text':'reader', 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(7, 3), 
    'size':(557, 152), 
    'label':'Spec File', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(20, 63), 
    'text':'Spec Path', 
    },

{'type':'TextField', 
    'name':'SpecPath', 
    'position':(91, 60), 
    'size':(400, -1), 
    },

{'type':'Button', 
    'name':'SpecPathSel', 
    'position':(499, 60), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl111', 
    'position':(19, 95), 
    'text':'Spec File(s)', 
    },

{'type':'Choice', 
    'name':'SpecFile', 
    'position':(91, 91), 
    'size':(273, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'SpecFileSel', 
    'position':(374, 91), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(20, 126), 
    'text':'Scan Num', 
    },

{'type':'ComboBox', 
    'name':'ScanNum', 
    'position':(91, 122), 
    'size':(78, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'ReadMed', 
    'position':(182, 124), 
    'size':(78, 20), 
    'label':'Read Med', 
    },

{'type':'CheckBox', 
    'name':'ReadXrf', 
    'position':(276, 126), 
    'label':'Read XRF', 
    },

{'type':'CheckBox', 
    'name':'ReadImg', 
    'position':(369, 126), 
    'size':(89, -1), 
    'label':'Read Image', 
    },

{'type':'Button', 
    'name':'Read', 
    'position':(477, 110), 
    'size':(72, 35), 
    'label':'Read Scan', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(24, 182), 
    'text':'Variable Name', 
    },

{'type':'ComboBox', 
    'name':'ScanVar', 
    'position':(124, 180), 
    'size':(186, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'AutoUpdateCheck', 
    'position':(319, 184), 
    'size':(72, 15), 
    'checked':True, 
    'label':'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoCalcVarName', 
    'position':(406, 184), 
    'size':(74, -1), 
    'label':'Auto Calc', 
    },

{'type':'CheckBox', 
    'name':'LongName', 
    'position':(494, 184), 
    'label':'Long', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(7, 223), 
    'size':(559, 175), 
    'label':'MED Params', 
    },

{'type':'StaticText', 
    'name':'medxrfPath', 
    'position':(12, 249), 
    'text':'Med/XRF Path', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'TextField', 
    'name':'MedPath', 
    'position':(97, 245), 
    'size':(400, -1), 
    },

{'type':'Button', 
    'name':'MedPathSel', 
    'position':(508, 246), 
    'size':(48, 22), 
    'label':'Select', 
    },

{'type':'StaticText', 
    'name':'Lbl1001', 
    'position':(18, 297), 
    'text':'XRF Lines =', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'ComboBox', 
    'name':'XrfLines', 
    'position':(99, 291), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'Align', 
    'position':(263, 294), 
    'checked':True, 
    'label':'Align', 
    },

{'type':'CheckBox', 
    'name':'Total', 
    'position':(263, 359), 
    'checked':True, 
    'label':'Total', 
    },

{'type':'StaticText', 
    'name':'McaListLbl', 
    'position':(20, 327), 
    'text':'Bad Mcas =', 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'ComboBox', 
    'name':'BadMcas', 
    'position':(99, 325), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'CorrectData', 
    'position':(263, 327), 
    'checked':True, 
    'label':'Correct', 
    },

{'type':'StaticText', 
    'name':'EminLbl', 
    'position':(11, 362), 
    'text':'Emin (keV) =', 
    },

{'type':'TextField', 
    'name':'Emin', 
    'position':(99, 358), 
    'size':(46, -1), 
    'text':'-1', 
    },

{'type':'StaticText', 
    'name':'TauListLbl', 
    'position':(351, 302), 
    'text':'Taus =', 
    'toolTip':'Provide Tdl variable holding Tau values', 
    },

{'type':'ComboBox', 
    'name':'McaTaus', 
    'position':(402, 298), 
    'size':(153, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'EmaxLbl', 
    'position':(149, 362), 
    'text':'Emax =', 
    },

{'type':'TextField', 
    'name':'Emax', 
    'position':(199, 358), 
    'size':(50, -1), 
    'text':'-1', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(333, 274), 
    'size':(233, 124), 
    'label':'Dead Time', 
    },

{'type':'Button', 
    'name':'FitDeadtime', 
    'position':(338, 342), 
    'size':(33, 39), 
    'label':'Fit', 
    },

{'type':'StaticText', 
    'name':'StaticText32', 
    'position':(398, 338), 
    'size':(20, 15), 
    'text':'X=', 
    },

{'type':'Choice', 
    'name':'DTX', 
    'position':(419, 334), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticText', 
    'name':'StaticText321', 
    'position':(378, 368), 
    'text':'Norm=', 
    },

{'type':'Choice', 
    'name':'DTNorm', 
    'position':(419, 365), 
    'size':(136, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(9, 396), 
    'size':(554, 110), 
    'label':'Image Params', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(8, 511), 
    'size':(309, 163), 
    'label':'Plot Scalers', 
    },

{'type':'Button', 
    'name':'PlotScaler', 
    'position':(22, 537), 
    'size':(41, 25), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'ScalerPlot', 
    'position':(83, 532), 
    'checked':True, 
    'label':'Auto Plot Scalers', 
    },

{'type':'CheckBox', 
    'name':'DefaultScalerAxes', 
    'position':(214, 535), 
    'checked':True, 
    'label':'Default Axes', 
    },

{'type':'StaticBox', 
    'name':'plotMedimage', 
    'position':(325, 515), 
    'size':(239, 159), 
    'label':'Plot Med/Image', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(343, 548), 
    'text':'Scan Point', 
    },

{'type':'ComboBox', 
    'name':'ScanPnt', 
    'position':(451, 545), 
    'size':(61, -1), 
    'items':[], 
    'text':'0', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(47, 586), 
    'text':'X=', 
    },

{'type':'Choice', 
    'name':'XPlot', 
    'position':(72, 587), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'XlogCheck', 
    'position':(262, 588), 
    'size':(45, -1), 
    'label':'Xlog', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(48, 615), 
    'text':'Y=', 
    },

{'type':'Choice', 
    'name':'YPlot', 
    'position':(72, 615), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'YlogCheck', 
    'position':(263, 616), 
    'label':'Ylog', 
    },

{'type':'Button', 
    'name':'PlotMed', 
    'position':(340, 586), 
    'size':(76, -1), 
    'label':'Plot Med', 
    },

{'type':'CheckBox', 
    'name':'MedYlog', 
    'position':(439, 591), 
    'label':'Ylog', 
    },

{'type':'CheckBox', 
    'name':'MedHold', 
    'position':(494, 592), 
    'size':(43, -1), 
    'label':'Hold', 
    },

{'type':'StaticText', 
    'name':'StaticText311', 
    'position':(24, 644), 
    'text':'Norm=', 
    },

{'type':'Choice', 
    'name':'NormPlot', 
    'position':(72, 645), 
    'size':(183, -1), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'HoldCheck', 
    'position':(84, 560), 
    'label':'Hold', 
    },

{'type':'Button', 
    'name':'PlotImg', 
    'position':(340, 628), 
    'size':(76, -1), 
    'label':'Plot Image', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(10, 683), 
    'size':(559, 6), 
    'layout':'horizontal', 
    },

] # end components
} # end background
] # end backgrounds
} }
