{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxCtr_bgTemplate',
          'title':u'Ctr Data',
          'size':(802, 811),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadCtr',
                   'label':u'ReadCtr',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveCtr',
                   'label':u'SaveCtr',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileWriteHKL',
                   'label':u'WriteHKL',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpDocumentation',
                   'label':u'Documentation',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(13, 54), 
    'size':(768, 4), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine51', 
    'position':(22, 674), 
    'size':(209, -1), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'HKCtrPlotInt', 
    'position':(164, 649), 
    'size':(68, -1), 
    'label':'Intensity', 
    },

{'type':'Button', 
    'name':'PlotAve', 
    'position':(674, 635), 
    'label':'Plot Ave', 
    },

{'type':'Button', 
    'name':'Average', 
    'position':(585, 635), 
    'label':'Average', 
    },

{'type':'Button', 
    'name':'SetImgArchive', 
    'position':(624, 26), 
    'size':(147, 24), 
    'label':'Set Image Archive Path', 
    },

{'type':'StaticText', 
    'name':'StaticText12', 
    'position':(19, 5), 
    'size':(-1, 21), 
    'text':'Select CtrData and ScanData objects from the variable list.  Use Set Image Path to globally change the path for all scan data.', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(19, 676), 
    'size':(211, 0), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(22, 637), 
    'size':(209, -1), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCtrHK', 
    'position':(82, 649), 
    'label':'Auto Plot', 
    },

{'type':'Button', 
    'name':'hkPlot', 
    'position':(18, 644), 
    'size':(57, 26), 
    'label':'HK Plot', 
    },

{'type':'TextArea', 
    'name':'SetData', 
    'position':(346, 79), 
    'size':(428, 61), 
    'text':'Data Set Information', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(17, 26), 
    'size':(143, 24), 
    'label':'Update Shell Variables', 
    },

{'type':'StaticText', 
    'name':'Lbl1', 
    'position':(163, 28), 
    'size':(-1, 15), 
    'text':'Ctr Variable Name', 
    },

{'type':'ComboBox', 
    'name':'CtrDataVar', 
    'position':(280, 26), 
    'size':(91, -1), 
    'items':[u''], 
    },

{'type':'Button', 
    'name':'AppendScan', 
    'position':(385, 26), 
    'size':(115, 24), 
    'label':'Append Scan', 
    },

{'type':'Choice', 
    'name':'AppendScanVar', 
    'position':(511, 26), 
    'size':(104, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(9, 59), 
    'size':(321, 185), 
    'label':'Data point', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(26, 77), 
    'text':'Point Index', 
    },

{'type':'StaticText', 
    'name':'StaticText10', 
    'position':(108, 77), 
    'text':'Bad Point', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(196, 77), 
    'text':'Integrate/Update', 
    },

{'type':'ComboBox', 
    'name':'PointNum', 
    'position':(22, 94), 
    'size':(69, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'Button', 
    'name':'PrevPoint', 
    'position':(20, 119), 
    'size':(35, 14), 
    'label':'<', 
    },

{'type':'Button', 
    'name':'NextPoint', 
    'position':(56, 119), 
    'size':(35, 14), 
    'label':'>', 
    },

{'type':'Button', 
    'name':'ToggleBad', 
    'position':(106, 97), 
    'size':(57, -1), 
    'label':'Toggle', 
    },

{'type':'Button', 
    'name':'PointUpdate', 
    'position':(187, 97), 
    'size':(57, -1), 
    'label':'Point', 
    },

{'type':'Button', 
    'name':'SetUpdate', 
    'position':(244, 97), 
    'size':(57, -1), 
    'label':'Set', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(19, 138), 
    'size':(295, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(21, 144), 
    'size':(217, -1), 
    'text':"On 'Point/Set' selection or append:", 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'CheckBox', 
    'name':'AutoIntegrate', 
    'position':(22, 167), 
    'size':(109, -1), 
    'checked':True, 
    'label':'Auto Integrate', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotIntegration', 
    'position':(151, 167), 
    'size':(149, -1), 
    'label':'Plot Integration (Fig 3)', 
    },

{'type':'CheckBox', 
    'name':'SetIntParams', 
    'position':(22, 191), 
    'size':(150, 20), 
    'label':'Set integration params', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(179, 197), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'>', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(212, 188), 
    'text':'Anchor  index:', 
    },

{'type':'CheckBox', 
    'name':'SetCorrParams', 
    'position':(22, 217), 
    'size':(149, -1), 
    'label':'Set correction params', 
    },

{'type':'Choice', 
    'name':'AnchorPointNum', 
    'position':(210, 206), 
    'size':(81, -1), 
    'items':[], 
    },

{'type':'TextArea', 
    'name':'PointData', 
    'position':(345, 143), 
    'size':(430, 94), 
    'editable':False, 
    'text':'Data Point Information\n', 
    },

{'type':'StaticBox', 
    'name':'StaticBox6', 
    'position':(10, 242), 
    'size':(775, 146), 
    'label':'Parameters', 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(338, 59), 
    'size':(448, 185), 
    'label':'Info', 
    },

{'type':'TextArea', 
    'name':'ParamDescr', 
    'position':(16, 263), 
    'size':(618, 85), 
    'editable':False, 
    'text':'Parameter Description', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(653, 264), 
    'text':'Copy Parameters: ', 
    },

{'type':'Button', 
    'name':'CopyParamsToAll', 
    'position':(649, 284), 
    'size':(51, 25), 
    'label':'All', 
    },

{'type':'Button', 
    'name':'CopyParamsToSet', 
    'position':(708, 284), 
    'size':(51, 25), 
    'label':'Set', 
    },

{'type':'StaticText', 
    'name':'StaticText11', 
    'position':(653, 318), 
    'text':'Copy Selected Param', 
    },

{'type':'Button', 
    'name':'ParamSet', 
    'position':(15, 352), 
    'size':(48, 27), 
    'label':'Set', 
    },

{'type':'TextField', 
    'name':'ParamName', 
    'position':(66, 353), 
    'size':(77, 26), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'ParamVal', 
    'position':(148, 353), 
    'size':(486, 26), 
    },

{'type':'Button', 
    'name':'CopySelParamToAll', 
    'position':(652, 338), 
    'size':(51, 25), 
    'label':'All', 
    },

{'type':'Button', 
    'name':'CopySelParamToSet', 
    'position':(710, 338), 
    'size':(51, 25), 
    'label':'Set', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(8, 389), 
    'size':(394, 168), 
    'label':'Integration Parameters', 
    },

{'type':'MultiColumnList', 
    'name':'IntParamList', 
    'position':(13, 409), 
    'size':(380, 142), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(408, 388), 
    'size':(375, 169), 
    'label':'Correction Parameters', 
    },

{'type':'MultiColumnList', 
    'name':'CorrParamList', 
    'position':(419, 409), 
    'size':(359, 142), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(7, 560), 
    'size':(413, 149), 
    'label':'Data Plots', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(21, 583), 
    'text':'Ctr Plot (Fig 0)', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(239, 578), 
    'size':(2, 127), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(258, 585), 
    'size':(131, 18), 
    'text':'Raw scan data (Fig 1)', 
    },

{'type':'StaticText', 
    'name':'colormap', 
    'position':(457, 590), 
    'text':'colormap', 
    },

{'type':'Button', 
    'name':'PlotCtr', 
    'position':(19, 606), 
    'size':(57, 26), 
    'label':'Full Plot ', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCtr', 
    'position':(82, 611), 
    'size':(70, 15), 
    'checked':True, 
    'label':'Auto Plot', 
    },

{'type':'Choice', 
    'name':'ColorMap', 
    'position':(439, 611), 
    'size':(105, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'PlotScanData', 
    'position':(256, 607), 
    'size':(50, -1), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotScan', 
    'position':(320, 611), 
    'size':(73, 19), 
    'label':'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'CtrPlotInt', 
    'position':(164, 611), 
    'size':(72, -1), 
    'label':'Intensity', 
    },

{'type':'StaticText', 
    'name':'ImaxLbl', 
    'position':(450, 639), 
    'text':'Image Max =', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(256, 639), 
    'size':(147, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(117, 583), 
    'text':'Columns =', 
    },

{'type':'TextField', 
    'name':'PlotCol', 
    'position':(191, 581), 
    'size':(34, 20), 
    'text':'2', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(258, 648), 
    'text':'Correction Plot (Fig 2)', 
    },

{'type':'Button', 
    'name':'SetPointClick', 
    'position':(20, 678), 
    'size':(77, 20), 
    'label':'Select Point', 
    },

{'type':'StaticBox', 
    'name':'box', 
    'position':(432, 561), 
    'size':(126, 147), 
    'label':'Image Plot Params', 
    },

{'type':'TextField', 
    'name':'Imax', 
    'position':(442, 660), 
    'text':'-1', 
    },

{'type':'Button', 
    'name':'SetPointsClick', 
    'position':(118, 678), 
    'size':(77, 20), 
    'label':'Select Set ', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(568, 561), 
    'size':(214, 147), 
    'label':'Symmetry / Averaging', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(584, 605), 
    'text':'Plane Group', 
    },

{'type':'Choice', 
    'name':'PlaneGroup', 
    'position':(665, 601), 
    'size':(72, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'CorrPlot', 
    'position':(256, 671), 
    'size':(50, -1), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCorr', 
    'position':(320, 676), 
    'label':'Auto Plot', 
    },

{'type':'Slider', 
    'name':'ImaxSlider', 
    'position':(439, 686), 
    'size':(104, 18), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':100, 
    },

] # end components
} # end background
] # end backgrounds
} }
