{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'wxCtr_bgTemplate',
          'title':u'Ctr Data',
          'size':(716, 794),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileReadCtr',
                   'label':u'ReadCtr',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveCtr',
                   'label':u'SaveCtr',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileWriteHKL',
                   'label':u'WriteHKL',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpDocumentation',
                   'label':u'Documentation',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'CheckBox', 
    'name':'HKCtrPlotInt', 
    'position':(138, 641), 
    'size':(59, -1), 
    'label':'Intensity', 
    },

{'type':'Button', 
    'name':'PlotAve', 
    'position':(599, 623), 
    'label':'Plot Ave', 
    },

{'type':'Button', 
    'name':'Average', 
    'position':(510, 625), 
    'label':'Average', 
    },

{'type':'Button', 
    'name':'SetImgArchive', 
    'position':(561, 7), 
    'size':(135, -1), 
    'label':'Set Image Archive Path', 
    },

{'type':'StaticText', 
    'name':'StaticText12', 
    'position':(22, 34), 
    'text':'Select a CtrData object and ScanData objects from the variable list.  Use Set Image Path to Globally change the path for all scan data.', 
    },

{'type':'StaticLine', 
    'name':'StaticLine6', 
    'position':(19, 664), 
    'size':(172, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine5', 
    'position':(20, 622), 
    'size':(173, -1), 
    'layout':'horizontal', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCtrHK', 
    'position':(72, 641), 
    'label':'Auto Plot', 
    },

{'type':'Button', 
    'name':'hkPlot', 
    'position':(18, 634), 
    'size':(49, 26), 
    'label':'HK Plot', 
    },

{'type':'TextArea', 
    'name':'SetData', 
    'position':(346, 69), 
    'size':(345, 61), 
    'text':'Data Set Information', 
    },

{'type':'Button', 
    'name':'Update', 
    'position':(12, 5), 
    'size':(122, 24), 
    'label':'Update Shell Variables', 
    },

{'type':'StaticText', 
    'name':'Lbl1', 
    'position':(140, 12), 
    'text':'Ctr Variable Name', 
    },

{'type':'ComboBox', 
    'name':'CtrDataVar', 
    'position':(236, 8), 
    'size':(91, -1), 
    'items':[u''], 
    },

{'type':'Button', 
    'name':'AppendScan', 
    'position':(342, 8), 
    'size':(84, 21), 
    'label':'Append Scan', 
    },

{'type':'Choice', 
    'name':'AppendScanVar', 
    'position':(439, 8), 
    'size':(104, -1), 
    'items':[], 
    },

{'type':'StaticBox', 
    'name':'StaticBox21', 
    'position':(9, 49), 
    'size':(321, 185), 
    'label':'Data point', 
    },

{'type':'StaticText', 
    'name':'Lbl11', 
    'position':(26, 67), 
    'text':'Point Index', 
    },

{'type':'StaticText', 
    'name':'StaticText10', 
    'position':(108, 67), 
    'text':'Bad Point', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(196, 67), 
    'text':'Integrate/Update', 
    },

{'type':'ComboBox', 
    'name':'PointNum', 
    'position':(22, 84), 
    'size':(69, -1), 
    'items':[u'0'], 
    'stringSelection':'0', 
    'text':'0', 
    },

{'type':'Button', 
    'name':'PrevPoint', 
    'position':(20, 109), 
    'size':(35, 14), 
    'label':'<', 
    },

{'type':'Button', 
    'name':'NextPoint', 
    'position':(56, 109), 
    'size':(35, 14), 
    'label':'>', 
    },

{'type':'Button', 
    'name':'ToggleBad', 
    'position':(106, 87), 
    'size':(57, -1), 
    'label':'Toggle', 
    },

{'type':'Button', 
    'name':'PointUpdate', 
    'position':(187, 87), 
    'size':(57, -1), 
    'label':'Point', 
    },

{'type':'Button', 
    'name':'SetUpdate', 
    'position':(244, 87), 
    'size':(57, -1), 
    'label':'Set', 
    },

{'type':'StaticLine', 
    'name':'StaticLine3', 
    'position':(19, 128), 
    'size':(295, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'text', 
    'position':(21, 134), 
    'size':(217, -1), 
    'text':"On 'Point/Set' selection or append:", 
    'toolTip':'Provide Tdl variable hodling values', 
    },

{'type':'CheckBox', 
    'name':'AutoIntegrate', 
    'position':(22, 157), 
    'size':(109, -1), 
    'checked':True, 
    'label':'Auto Integrate', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotIntegration', 
    'position':(151, 157), 
    'size':(149, -1), 
    'label':'Plot Integration (Fig 3)', 
    },

{'type':'CheckBox', 
    'name':'SetIntParams', 
    'position':(22, 181), 
    'size':(150, 20), 
    'label':'Set integration params', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(179, 187), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'>', 
    },

{'type':'StaticText', 
    'name':'Lbl3', 
    'position':(212, 178), 
    'text':'Anchor  index:', 
    },

{'type':'CheckBox', 
    'name':'SetCorrParams', 
    'position':(22, 207), 
    'size':(149, -1), 
    'label':'Set correction params', 
    },

{'type':'Choice', 
    'name':'AnchorPointNum', 
    'position':(210, 196), 
    'size':(81, -1), 
    'items':[], 
    },

{'type':'TextArea', 
    'name':'PointData', 
    'position':(345, 133), 
    'size':(349, 94), 
    'editable':False, 
    'text':'Data Point Information\n', 
    },

{'type':'StaticBox', 
    'name':'StaticBox6', 
    'position':(10, 232), 
    'size':(689, 146), 
    'label':'Parameters', 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(338, 49), 
    'size':(360, 185), 
    'label':'Info', 
    },

{'type':'TextArea', 
    'name':'ParamDescr', 
    'position':(16, 253), 
    'size':(542, 85), 
    'editable':False, 
    'text':'Parameter Description', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(573, 254), 
    'text':'Copy Parameters: ', 
    },

{'type':'Button', 
    'name':'CopyParamsToAll', 
    'position':(569, 274), 
    'size':(51, 25), 
    'label':'All', 
    },

{'type':'Button', 
    'name':'CopyParamsToSet', 
    'position':(628, 274), 
    'size':(51, 25), 
    'label':'Set', 
    },

{'type':'StaticText', 
    'name':'StaticText11', 
    'position':(573, 308), 
    'text':'Copy Selected Param', 
    },

{'type':'Button', 
    'name':'ParamSet', 
    'position':(15, 342), 
    'size':(48, 27), 
    'label':'Set', 
    },

{'type':'TextField', 
    'name':'ParamName', 
    'position':(66, 343), 
    'size':(77, 26), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'ParamVal', 
    'position':(148, 343), 
    'size':(410, 26), 
    },

{'type':'Button', 
    'name':'CopySelParamToAll', 
    'position':(572, 328), 
    'size':(51, 25), 
    'label':'All', 
    },

{'type':'Button', 
    'name':'CopySelParamToSet', 
    'position':(630, 328), 
    'size':(51, 25), 
    'label':'Set', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(8, 379), 
    'size':(328, 172), 
    'label':'Integration Parameters', 
    },

{'type':'MultiColumnList', 
    'name':'IntParamList', 
    'position':(14, 399), 
    'size':(316, 145), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(342, 379), 
    'size':(355, 174), 
    'label':'Correction Parameters', 
    },

{'type':'MultiColumnList', 
    'name':'CorrParamList', 
    'position':(351, 399), 
    'size':(339, 146), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':['Name', 'Value'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(9, 555), 
    'size':(339, 142), 
    'label':'Data Plots', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(18, 575), 
    'text':'Ctr Plot (Fig 0)', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(201, 568), 
    'size':(2, 127), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(219, 575), 
    'size':(131, 18), 
    'text':'Raw scan data (Fig 1)', 
    },

{'type':'StaticText', 
    'name':'colormap', 
    'position':(382, 580), 
    'text':'colormap', 
    },

{'type':'Button', 
    'name':'PlotCtr', 
    'position':(19, 596), 
    'size':(49, 26), 
    'label':'Full Plot ', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCtr', 
    'position':(72, 601), 
    'size':(61, 15), 
    'checked':True, 
    'label':'Auto Plot', 
    },

{'type':'Choice', 
    'name':'ColorMap', 
    'position':(364, 601), 
    'size':(105, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'PlotScanData', 
    'position':(217, 597), 
    'size':(42, -1), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotScan', 
    'position':(264, 599), 
    'size':(73, 19), 
    'label':'Auto Plot', 
    },

{'type':'CheckBox', 
    'name':'CtrPlotInt', 
    'position':(138, 602), 
    'size':(59, -1), 
    'label':'Intensity', 
    },

{'type':'StaticText', 
    'name':'ImaxLbl', 
    'position':(375, 629), 
    'text':'Image Max =', 
    },

{'type':'StaticLine', 
    'name':'StaticLine4', 
    'position':(211, 626), 
    'size':(127, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(95, 575), 
    'text':'Columns =', 
    },

{'type':'TextField', 
    'name':'PlotCol', 
    'position':(154, 574), 
    'size':(34, 20), 
    'text':'2', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(214, 630), 
    'text':'Correction Plot (Fig 2)', 
    },

{'type':'Button', 
    'name':'SetPointClick', 
    'position':(17, 671), 
    'size':(77, 20), 
    'label':'Select Point', 
    },

{'type':'StaticBox', 
    'name':'box', 
    'position':(357, 560), 
    'size':(126, 138), 
    'label':'Image Plot Params', 
    },

{'type':'TextField', 
    'name':'Imax', 
    'position':(367, 650), 
    'text':'-1', 
    },

{'type':'Button', 
    'name':'SetPointsClick', 
    'position':(107, 672), 
    'size':(77, 20), 
    'label':'Select Set ', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(493, 559), 
    'size':(202, 139), 
    'label':'Symmetry / Averaging', 
    },

{'type':'StaticText', 
    'name':'StaticText31', 
    'position':(520, 595), 
    'text':'Plane Group', 
    },

{'type':'Choice', 
    'name':'PlaneGroup', 
    'position':(590, 591), 
    'size':(72, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'CorrPlot', 
    'position':(217, 656), 
    'size':(42, -1), 
    'label':'Plot', 
    },

{'type':'CheckBox', 
    'name':'AutoPlotCorr', 
    'position':(264, 660), 
    'label':'Auto Plot', 
    },

{'type':'Slider', 
    'name':'ImaxSlider', 
    'position':(364, 676), 
    'size':(104, 18), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':False, 
    'value':100, 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(21, 735), 
    'text':'Add: select plane group and calculate / plot averages.  Under file we need to read / write ctr files (as hdf)', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(9, 762), 
    'size':(691, 6), 
    'layout':'horizontal', 
    },

] # end components
} # end background
] # end backgrounds
} }
